### ISSUE TITLE
SBDH detector

### ISSUE THREAD

**Issue by monze** [difi/oxalis#129]
The current way of identifying, if a document already contain a SBDH is not very solid. Method from the DocumentSniffer:
  
          for (int i = 0; i < 50 && (line = bufferedReader.readLine()) != null; i++) {
                if (line.contains("<StandardBusinessDocument")) {
                    sbdhDetected = true;
                    break;
                }
            }
  
If, for instance a document contain a xml comment element, that include the text '<StandardBusinessDocument', the sniffer will identify it as the document contain the SBDH.

Why not open the document as an xml, and look at the default namespace of the root element. That namespace should unique identify the document type.

Jacob Mogensen
mySupply ApS

**Comment by ManjeetYadav** [comment]
I agree with both points and Jacob just gave a proposal for better detection, you Thor can think how to handle the prefixed namespace but the detection of SBDH should be improved definitely. There are ways to identify the root element with prefix as well. In case of prefix, the namespace should be in similar way:
e.g. 
<StandardBusinessDocument xmlns="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader"> 
OR
<prefix:StandardBusinessDocument xmlns:prefix="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader">

**Comment by teedjay** [comment]
Marked this to be fixed in next version.  The potential prefix issue has to be dealt with.
