### ISSUE TITLE
While sending through AS2 protocol, we get same type of exception for document error or network problem.

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#170]
While sending through AS2 protocol, we get same type of exception even though problem is in document or some network problem.

Problem in document content, exception thrown is: 
throw new IllegalStateException("Transmission request can not be built, some metadata was missing");

Problem in network ( connecting to receiving AP), exception thrown is: 
java.lang.IllegalStateException: Unexpected error during execution of http POST to https://abc/oxalis/as2: abc

I agree exception message is different, but exception type is same. 

Don't you think, for network issue we should throw error like: 
java.net.UnknownHostException: abc  or something similar. 

Network errors are very much differentiated in START protocol. It throw exception which is subclass of: javax.xml.ws.WebServiceException

There must be mechanism to differentiate between content problem and network problem.

**Comment by steinarcook** [comment]
Will be fixed in #227
