### ISSUE TITLE
AP traffic statistics report : Statistics servlet vs CommandLine tool 

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#202]
Currently some AP exposed statistics servlet publically to share traffic report with DIFI. 
While other AP send it manually (because of some concern)

Is it possible for you to provide command-line tool to generate and dump statistics report (favorably in XML format) based on parameter (date  - start date, end-date) ?

This report can be used for viewing it locally (without cipers/encryption). It can also be used to share it with DIFI by those AP which prefer manual way.

**Comment by steinarcook** [comment]
You are welcome to write such a tool and publish it as open source :-)
