### ISSUE TITLE
Please allow system properties to be used for OXALIS_HOME

### ISSUE THREAD

**Issue by milanaleksic** [difi/oxalis#203]
We are using the oxalis standalone for end2end testing. There is at this time only one issue: we have to patch the Oxalis standalone JAR to allow System properties to be looked into in search for OXALIS_HOME property.
Please add support for this if possible

**Comment by teedjay** [comment]
Make sure we write the selected path to the log / output when booting.

Will use the first value found using this order :
-D OXALIS_HOME=/some/path  (Java VM property)
$OAXLIS_HOME (OS env setting)
~/.oxalis (HOME folder .oxalis folder)

**Comment by teedjay** [comment]
Oxalis will now look for OXALIS_HOME using this order :
1 - Directory referenced by Local JNDI Context java:comp/env/OXALIS_HOME
2 - Directory referenced by Java System Property -D OXALIS_HOME
3 - Directory referenced by Environment Variable $OXALIS_HOME
4 - Directory .oxalis inside the home directory of the user
