### ISSUE TITLE
MessageId in the SBDH and PeppolMessageMetaData JSON data file

### ISSUE THREAD

**Issue by monze** [difi/oxalis#207]
We are using the Oxalis 3.2.0-SNAPSHOT (the released version).

I'm performing a test, where I send a document from Oxalis, to our receiving Oxalis endpoint. The receiving Oxalis store the xml file and a PeppolMessageMetaData JSON data file.
In the data file, there is a MessageId.

I have noticed that when we create a SBDH, it also contains a messageId - the unique id for the envelope. I would have expected that it was this id, which was stored in the MessageId in the JSON data file. 
However, this is not the case..

In fact, I cannot find the SBDH messageId on the receiving side. The messageId is unique for the envelope, so it is perfect to make a double check, to validate if the document (the envelope) already was received. 

Should theses two MessageId be the same?
If not, what is the intended use for the MessageId on the receiving side?

Jacob Mogensen
mySupply ApS

**Comment by teedjay** [comment]
I think you might have found a bug - the InstanceIdentifier on the SBDH is just a random UUID right now (and not the actual MessageID which is returned in the JSON).

From the JSON response you should get  :
- TransmissionID (a UUID of the actual transfer, this is globally unique for every AS2 / START transmission)
- MessageID which uniquely identify the payload (for AS2 the payload is the full SBDH envelope, and the MessageID should be found as .../DocumentIdentification/InstanceIdentifier)

**Comment by teedjay** [comment]
Small change in  logic to preserve MessageId, either random UUID generated by Oxalis or MessageId retrieved from SBDH of pre-wrapped message.

(1) Example document without SBDH (Oxalis wraps in SBDH)
Generate current date and random MessageId
Mon Mar 16 17:26:54 CET 2015
b1bb076e-6f2d-4221-90f2-6bc0d9039fdd

TransmissionId
0bd81c42-8d42-40e9-ac00-b690981c313c

TransmissionResponse returns all 3 values
Mon Mar 16 17:26:54 CET 2015
b1bb076e-6f2d-4221-90f2-6bc0d9039fdd
0bd81c42-8d42-40e9-ac00-b690981c313c

Standalone output :
Message using messageId b1bb076e-6f2d-4221-90f2-6bc0d9039fdd sent to https://ap.unit4.com/oxalis/as2 using AS2 was assigned transmissionId 0bd81c42-8d42-40e9-ac00-b690981c313c

From received SBDH at accesspoint :
<InstanceIdentifier>b1bb076e-6f2d-4221-90f2-6bc0d9039fdd</InstanceIdentifier>
<CreationDateAndTime>2015-03-16T17:27:29.526+01:00</CreationDateAndTime>

(2) Example document already wrapped in SBDH (Oxalis uses SBDH values) 
Current date and MessageId already present in SBDH
2014-11-01T16:32:48.128+01:00
7eed9a1-d9a1-d9a1-d9a1-7eed9a1

TransmissionId
a215d606-9940-47f9-bdfd-58150621755c

TransmissionResponse returns all 3 values
Sat Nov 01 16:32:48 CET 2014
7eed9a1-d9a1-d9a1-d9a1-7eed9a1
a215d606-9940-47f9-bdfd-58150621755c

Standalone output :
Message using messageId 7eed9a1-d9a1-d9a1-d9a1-7eed9a1 sent to https://ap.unit4.com/oxalis/as2 using AS2 was assigned transmissionId a215d606-9940-47f9-bdfd-58150621755c

From received SBDH at accesspoint :
<InstanceIdentifier>7eed9a1-d9a1-d9a1-d9a1-7eed9a1</InstanceIdentifier>
<CreationDateAndTime>2014-11-01T16:32:48.128+01:00</CreationDateAndTime>

**Comment by teedjay** [comment]
Added integration test and pushed.
