### ISSUE TITLE
XML External Entity vulnerability in oxalis?

### ISSUE THREAD

**Issue by GjestadM** [difi/oxalis#208]
It looks like Oxalis are vulnerable to XXE (see https://www.owasp.org/index.php/XXE)
The consequence can be that receiving access point that uses oxalis can be subjected to DOS attacks eg using XML bomb (https://cytinus.wordpress.com/2011/07/26/37/)
or sender can extract file content from production servers (passwords or other confidential information).

We have looked in Oxalis sourcecode for fixes, but have not found anyone.
Are you aware of this potential vulnerability?
If analysis is not done, when will this be done?

**Comment by teedjay** [comment]
Thanks for your input - will have to read up on the subject a bit before analyzing.

**Comment by steinarcook** [comment]
Fixed by adding the following code:
```java
        // Prevents XML entity expansion attacks
        dbFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true);
```
