### ISSUE TITLE
While monitoring traffic, we found cases where documents of some of participant are routed through our system even though those participant are not registered with us

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#209]
Scenario:
We are receiving documents of some of participants through our peppol incoming interface. These participants are not registered with us.
Since our routing do not resolve those receiver, so those document again use our peppol outgoing interface to find the recipient.

So my suggestion is that we must not received documents of participants which are not registered with us. This strange behavior is using our infrastructure intentionally or unintentionally.

So it will be good to add this behavior in at least production mode so that it is still possible to run tests regardless of origin of message.

**Comment by teedjay** [comment]
I add this from an earlier mail from Arun Kumar : 

> There was restriction in START protocol about this. e.g see following code snippet in :
> void verifyThatThisDocumentIsForUs(PeppolMessageMetaData peppolMessageMetaData) {...}
