### ISSUE TITLE
NL:ION should be changed to NL:OIN

### ISSUE THREAD

**Issue by ManjeetYadav** [difi/oxalis#210]
Peppol says 9954 as NL:ION, see here: https://joinup.ec.europa.eu/svn/peppol/TransportInfrastructure/PEPPOL_Policy%20for%20use%20of%20identifiers-300.pdf  and also oxalis code which wraps SBDH use NL:ION. 

Simpler-invoicing use NL:OIN (Overheids Identificatie Nummber) at all places of official Simpler Invoicing documentations, schmeatrons and SMPs(Galaxy SMP) etc. which is correct. 

Could you please change all occurrences of NL:ION to NL:OIN in oxalis code and peppol documentations asap as a Simpler-invoicing customer go-live is being affected because of this.

Let us know if more details are needed.

Thanks and Regards,
Manjeet Yadav

**Comment by teedjay** [comment]
Fixed NL:OIN in latest Oxalis snapshot release.

**Comment by aaron-kumar** [comment]
Can you please add it to Oxalis 3.1.0 release?

It is urgently required.

**Comment by klakegg** [comment]
Oxalis 3.1.0 is the previous release, not an upcoming release. You are free to patch your version.

**Comment by aaron-kumar** [comment]
agree!
