### ISSUE TITLE
The PeppolProcessTypeId is required to start with 'urn:' which is too strick

### ISSUE THREAD

**Issue by monze** [difi/oxalis#216]
When we try to send a document using Oxalis, we provide the SBDH data to Oxalis. We have already extracted them from the document. In a test, I tried to send a Danish OioUbl document using the PEPPOL infrastructure and Oxalis.
However, in the Danish document standard OioUbl, almost all our Profile name (PeppolProcessTypeId) start with 'Procurement-...', so I get the IllegalArgumentException("PEPPOL process ......);.

See Class eu.peppol.identifier.PeppolProcessTypeId

```
if (!processTypeIdentifer.startsWith("urn:")) {
         throw new IllegalArgumentException("PEPPOL process type identifier should start with \"urn\"");
}
```

This check is of the same kind of restriction as in bug 184, that restrict the use of Oxalis, and is undesirable. It can't be expected that all profiles that is ever gonna be used, will start with 'urn:'.

Jacob Mogensen
mySupply ApS

**Comment by aaron-kumar** [comment]
Wasn't it should be log.warn instead of log.info

**Comment by klakegg** [comment]
For what reason should an application log warnings when using perfectly legal input values? Using values not starting with "urn:" is currently by design in Denmark.

**Comment by aaron-kumar** [comment]
What is the purpose of log.info or condition itself than? Let be flexible
than...

**Comment by klakegg** [comment]
You can't have both log.warn and no log.* at the same time.
