### ISSUE TITLE
Using Oxalis as lookUp

### ISSUE THREAD

**Issue by monze** [difi/oxalis#217]
We are working on improving our code and integration with Oxalis. I this scenario, we have received a document from one customer, which we now must deliver to another customer (Seen from our point of view). 
However, we have multi ways to deliver the document, so we must decide which method to use, either we must use Oxalis and Peppol, or use the danish NemHandel infrastructure, or use email, ect.. This can be seen as a prioritized ordered list, where we will send using the first method, that we can send the document.
The trick is, that we have not even created the document. Based on the sending technology, we will create a valid document for that infrastructure.

So we need to make Oxalis perform a Lookup, and see if it can send the document.
At the moment, we use the TransmissionRequestBuilder, to build the TransmissionRequest. However, the build method require that the document exist, as it will parse the document to see if the PeppolStandardBusinessHeader data is correct. We have the data, and have provided it to the TransmissionRequestBuilder, but it still parse the document - which does not exist.

I can disable this behavior by doing this
```
GlobalState.getInstance().setTransmissionBuilderOverride(true);
```
However, this is not the correct way, as the comment for this method state

```
    /**
     * This is here to assist UNIT tests only, and should NOT be used in production.
     * Makes it possible to override in runtime as well as using environment variable
     */
    public void setTransmissionBuilderOverride(boolean transmissionBuilderOverride) {
        this.transmissionBuilderOverride = transmissionBuilderOverride;
    }
```

So I need a way to disable the parsing of the document, as the document does not exist.

The next issue is, that the parsing only allowed know documents, see
eu.peppol.document.PlainUBLHeaderParser.createDocumentParser(). Because it is implemented like this, means that we can't add another document type, without updating the source code. Even though we have provided the information that must be used in the SBDH, the sending will failed, as the document can not be parsed.
This also means, that you must implement every document types, that is ever gonna be used in Peppol. For instance, if a Spanish national standard is approved by Peppol, you must update the source code, to include this document too. This is a maintainers nightmare - just thing of all the different document types there potential exist, in different countries, in different industries like the finances sector.

This is a very big restriction, and not necessary. It is NOT Oxalis that should guaranties, that what is put in the SBDH, also is the same as exist in the document.

It does make sense to parse the document and retrieve the information, if no PeppolStandardBusinessHeader data is provided. But if they are provided, the parsing does in best case nothing, and in worst case, stop a valid dokument, as it is unknown to Oxalis.

Jacob Mogensen
mySupply ApS

**Comment by klakegg** [comment]
Why would you use a sending mechanism for lookup and not just the lookup mechanism provided by the SmpLookupManager? Also, this is not fancy technology, so creating your own lookup service is done by a minimal of effort.

**Comment by teedjay** [comment]
To use SmpLookupManager check out eu.peppol.outbound.OxalisOutboundModule from oxalis-outbound module.  Your code could be something like this : 

OxalisOutboundModule oom = new OxalisOutboundModule();
SmpLookupManager slm = oom.getSmpLookupManager();

Then you can check specific receiver + document type using : slm.getServiceMetaData(...)
Or retrieve a list over all document types the receiver accepts : slm.getServiceGroups(...)

**Comment by monze** [comment]
@klakegg
The is a good reason not to do as you suggests, but it does require some explanation. Please read below.

@teedjay
If I do as you suggests, we can end up in some undesired state. Again it does require some explanation. Please read below.


This is the situation that can/will happen if we follow yours suggestion.
If we try to lookup using SmpLookupManager, we can get a positive response back - indication that the document can be send. Then we can create it, and will sent it using Oxalis.

Oxalis then try to parse the document, which can fail, if it does not know the document type.... We are know in a deadlook, where all test indicate that the sending can be performed with success, but can never actually be performed when trying.

I have already tried this situation locally in a small test, as I had registered a old danish document format (OIOXML), that is not based on UBL 2. The registration was performed, and lookup was successful, but sending always failed, as the document could not be parsed.

Therefore, whatever extra test there is perform when sending, must also be perform in the lookup validation. So if we use the SmpLookupManager, to make the lookup, I must manually implement the same test (the parsing), as already exist in the TransmissionRequestBuilder. Else I will not get a correct/valid answer back.
By doing this, I will have duplicated code, that perform the same test. This violate against good programming principles (DRY). If you update the code in TransmissionRequestBuilder, there suddenly inconsistency between the two code parts.

@klakegg
That is the reason why ALWAYS use the same code, if possible. So it really does make sense to use the sending mechanism, also to make a lookup check.

@teedjay
Actually, what you suggest, is a simple loop-up to see what is registered in PEPPOL, and not a verification about whether or not the document can be sent. It is to different things, and we need the later.



Last, none of you comment on the parsing of the document, which is actually the big problem.
```
eu.peppol.document.PlainUBLHeaderParser.createDocumentParser()
```

Jacob Mogensen
mySupply ApS

**Comment by teedjay** [comment]
What you should do is make the SMP lookup in advance to see which formats the receiver accepts.  If you can produce a format the receiver accepts you just create that format and put it on your "oxalis queue".  Otherwise you put it on one of your other "outbound queues", like mail, sftp, whatever.

The parsing we do in the Transmitter is just there to prevent you from sending something wrong or to someone other that you specify.  The logic was supposed to just accept "new and unknown formats" as long as you have specified the mandatory properties using the TransmissionRequestBuilder.

Since this fails in your scenario we should really fix the logic on the transmitter side of Oxalis.  We run lots of automated tests against different formats to make sure they pass this logic.

If you could mail me a few example documents that fail we should be able to fix the logic so that your OIOXML (or other formats) would be accepted and sendt.
