### ISSUE TITLE
Case sensitive in content-type field

### ISSUE THREAD

**Issue by elfogre** [difi/oxalis#219]
I'm Jose Escobar from Edicom. Currently I'm testing our Peppol AP implementation against your test server (9908:810418052 ) and I had some problem to get a valid MDN response. By default, our AS2 server sends content-type value field in uppercase, like Content-Type: APPLICATION/XML, but your server response with an error in the MDN:

The message sent to AS2 System id APP_1000000097 on Mon, 27 Jul 2015 17:08:59 +0200 with subject AS2 MDN as you requested has been received.
It has been processed
The warning/error message is :
ERROR: Unable to get content of message.can't extract input stream: java.io.IOException: Cannot convert DataSource with content type "APPLICATION/XML" to object in XmlDataContentHandler

So I tried again with a lowercase content type: Content-Type: application/xml. Your MDN response in this case indicates no error:

The message sent to AS2 System id APP_1000000097 on Mon, 27 Jul 2015 17:35:56 +0200 with subject AS2 MDN as you requested has been received.
It has been processed successfully.

Mic value is correct, all works fine and I can see my message in https://test-aksesspunkt.difi.no/inbound/9908_810418052/9915_test/

HTTP protocol header rfc http://www.w3.org/Protocols/rfc1341/4_Content-Type.html#z0 says that content-type value is not case sensitive. Could you please check it?

**Comment by teedjay** [comment]
Seems like there could be a bug in the library we use for mime-parsing.

**Comment by steinarcook** [comment]
You are probably right, when it comes to Content-type. 

However; when it comes to mime types I think you will find that all MIME types are case sensitive.

Have a look at the list at http://www.iana.org/assignments/media-types/media-types.xhtml

I suggest you change your code to use «application/xml» in order to make things work :-)

We might consider changing this in a future release if it turns out that MIME types are case insensitive.

**Comment by teedjay** [comment]
Looks like MIME types should be treated case insensitive even if they by convention / best practice should be lower cased.

As far as I can see the MIME RFC states that for Content-Type both type and subtype are case insensitive : https://www.ietf.org/rfc/rfc2045.txt

At page 11 (Chapter 5.1.  Syntax of the Content-Type Header Field) : 

     content := "Content-Type" ":" type "/" subtype
                *(";" parameter)
                ; Matching of media type and subtype
                ; is ALWAYS case-insensitive.

**Comment by steinarcook** [comment]
You are right, of course. However, I regard this like using national characters in your e-mail address or web site url. Do you want your e-mail to arrive or do you want to be a purist with regards to standards?

**Comment by klakegg** [comment]
The Exception is tracked back to code in rt.jar, indicating content-type as lowercase is the de facto standard.

**Comment by monze** [comment]
To state that 'de facto standard' of the content type is lower case, might be too narrow looking at PEPPOL as global network... so why not wrap it in Oxalis? It has already been registered as a bug in java: https://java.net/jira/browse/JAX_WS-1176?jql=text%20~%20%22XmlDataContentHandler%22
