### ISSUE TITLE
Signers certificate is not validated

### ISSUE THREAD

**Issue by carlowitz** [difi/oxalis#220]
Hello, 
We are testing Oxalis and checked out the server from "oxalis-3.1.1-release-difi" tag which we think is the one to use for a production environment? Please correct us if we are wrong. 

Seems however as the signers certificate is unvalidated in the AS2 protocol. The eu.peppol.as2.SignedMessageInspector.parseSignedMessage() method has the row commented out with: 
// TODO validateCertificate(signersX509Certificate);

If this is uncommented, the validation fails with java.lang.IllegalStateException: Unable to trust the signer : missing provider

The reason for this seems to be that method validateCertificate creates a Sun provider in this row
CertPathValidator pathValidator = CertPathValidator.getInstance(CertPathValidator.getDefaultType());

My guess is that the BouncyCastleProvider should be used instead since it works if we use:
CertPathValidator pathValidator = CertPathValidator.getInstance("PKIX",PROVIDER_NAME);

This can be tested if you add this method to the eu.peppol.as2.SignedMimeMessageInspectorTest

   @Test
    public void testParseSignedMessage() throws Exception {
        SignedMimeMessageInspector signedMimeMessageInspector = new SignedMimeMessageInspector(signedMimeMessage);
        try {
            signedMimeMessageInspector.parseSignedMessage();
        } catch (Exception e){
            assertTrue(false, e.getMessage());
        }
        assertTrue(true);
    }

Best regards /Fredrik Carlowitz XPS

**Comment by steinarcook** [comment]
Thanks! How about you create a Git pull request and we can implement it?

**Comment by carlowitz** [comment]
Sure, think you should see it now? /Thanks!

**Comment by steinarcook** [comment]
Thanks, I have just merged your modification.

On 20 August 2015 at 07:56, Fredrik Carlowitz <notifications@github.com>
wrote:

> Sure, think you should see it now? /Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/difi/oxalis/issues/220#issuecomment-132901844>.
>



-- 
Steinar Overbeck Cook

**Comment by teedjay** [comment]
Marked as fixed in milestone 3.2
