### ISSUE TITLE
Remove BIS document sniffing and SBD encapsulation

### ISSUE THREAD

**Issue by steinarcook** [difi/oxalis#226]
Current implementation inspects supplied document to determine the XML document type (scheme). If no SBD/SBDH (Standard Business Document with Standard Business Document Header and accompanying payload) detected:
1. Parse the XML document to determine the PEPPOL Document type identifier and process identifier
2. Create SBD with appropriate SBDH
3. Wrap supplied document in SBD
4. Commence transfer of document.

In the future all documents will be rejected unless they have been wrapped in an envelope according to the PEPPOL standards. This will be done in two phases:
1. Refactor the current sniffing and wrapping into a separate component and deactivate this feature by default in `oxalis-global.properties`. This will alow the operator to explicitly activate the feature if needed.
2. Remove the feature from the code. 

The end result: all messages must be wrapped according to PEPPOL standard _before_ being submitted into Oxalis for transportation.

The sniff&wrap code will continue to be available for those wishing to implement their own value added services.

**Comment by klakegg** [comment]
As of 4.0.1 is detection and wrapping pluggable. Default configuration may change when current detection code no longer works with current PEPPOL BIS document specifications.

**Comment by jannewaren** [comment]
Do you have any updates for this one? What's your plan? Sending a Peppolbis30 will not work currently with Oxalis without doing the SBD/SBDH wrapping separately before giving the payload to oxalis-outbound.

Do you plan to fix it for Peppolbis30 (I think what's failing are the participant SchemeID's) or just tell users to construct the SBD/SBDH themselves and stop relying on Oxalis for that?

Would be nice to know this in advance as it might be quite a big change for AP providers.

**Comment by klakegg** [comment]
The original issue contains this statement:

> In the future all documents will be rejected unless they have been wrapped in an envelope according to the PEPPOL standards. 

I think that would descibe the plan quite well. The module in question contains a README file describing the expected future of module.

Based on the information above, I see no reason to make any changes to handle PEPPOL BIS 3.0 document types.
