### ISSUE TITLE
SMP lookup fails for Synsam Norge AS

### ISSUE THREAD

**Issue by teedjay** [difi/oxalis#235]
When doing getServiceGroups() lookup for 9908:994496093 the Sax parser fails with "Content is not allowed in prolog".  This seems to be caused by a newline character between prolog and content received from the Swedish SMP (smp.scancloud.se).

To reproduce the error add the following failing test to SmpLookupManagerImplTest :

```java
    @Test
    public void testGetServiceGroupProblematicOrgNumber() throws SmpLookupException, ParticipantNotRegisteredException {
        List<PeppolDocumentTypeId> documentTypeIdList = smpLookupManager.getServiceGroups(new ParticipantId("9908:994496093"));
        assertTrue(!documentTypeIdList.isEmpty());
    }
```

**Comment by steinarcook** [comment]
The problem is not a new line character. The problem is that the SMP is serving an XML with a "byte order mark", which is mandatory for UTF-16 and UTF-32 but optional for UTF-8 as it gives no meaning.

```
$ od -t xC -t a t | head
0000000    ef  bb  bf  3c  3f  78  6d  6c  20  76  65  72  73  69  6f  6e
           ?   ?   ?   <   ?   x   m   l  sp   v   e   r   s   i   o   n
0000020    3d  22  31  2e  30  22  20  65  6e  63  6f  64  69  6e  67  3d
           =   "   1   .   0   "  sp   e   n   c   o   d   i   n   g   =
0000040    22  75  74  66  2d  38  22  3f  3e  0d  0a  3c  6e  73  32  3a
           "   u   t   f   -   8   "   ?   >  cr  nl   <   n   s   2   :
0000060    53  65  72  76  69  63  65  47  72  6f  75  70  20  78  6d  6c
           S   e   r   v   i   c   e   G   r   o   u   p  sp   x   m   l
0000100    6e  73  3a  6e  73  34  3d  22  68  74  74  70  3a  2f  2f  77
           n   s   :   n   s   4   =   "   h   t   t   p   :   /   /   w
```

This is a problem caused by the underlying XML parser provided by the JDK. 

I would strongly suggest that you contact Scancloud and tell them to stop emitting "byte order marks" in their XML as it causes problem.s

**Comment by teedjay** [comment]
At first I was thinking about a BOM issue like you, but since they use a correct and legal UTF-8 BOM it would be strange if newer Java versions like Java 7 and Java 8 doesn't support and handle that correctly.

And since whitespaces are not allowed before the XML declaration, and this file clearly has both 0d 0a before the declaration, I was leaning towards that conclusion.

Either way - smp.scancloud.se has been alerted.

**Comment by teedjay** [comment]
Scancloud has issued a fix to their SMP so that it no longer returns BOM on UTF8.
The support number at Scancloud for this was "(SUPPORT-23777) Issue with your SMP lookup".
