### ISSUE TITLE
Shall TransmissionId or AS2 Message-Id(Not the MessageId in SBDH) be mandatory to obey UUID pattern? If not, shouldn't it?

### ISSUE THREAD

**Issue by ManjeetYadav** [difi/oxalis#244]
We are having a problem that some Access points sending custom transmissionId or AS2 Message-Id and not in the uuid pattern. Shouldn't it be mandatory to have uuid pattern for it?

Weird thing I found is that the AS2 Message-Id used in examples here https://joinup.ec.europa.eu/svn/peppol/TransportInfrastructure/ICT-Transport-AS2_Service_Specification-2014-01-15.pdf are also not following the uuid pattern and doesn't seems to be any guideline there.

Seems 1 AP also using similar pattern for their AS2 Message-Id , maybe due to the example referred in above document.

Would you be able to assist in getting these answers please?

**Comment by steinarcook** [comment]
The are no requirements syaing that the Message-Id header should use the UUID pattern.
