### ISSUE TITLE
What is expected 'release' date for Oxalis 3.2?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#245]
We are waiting for fix provided as part of following issues:
1. https://github.com/difi/oxalis/issues/203
2. https://github.com/difi/oxalis/issues/205

We are expecting release from long time. What are hurdles in release oxalis 3.2?

**Comment by steinarcook** [comment]
Oxalis is open source.

Feel free to roll your own release whenever it suits you. You may also supply you proposed changes in code through a GitHub «pull request» :-)
