### ISSUE TITLE
Incorrect case header on MdnMimeMessageInspector

### ISSUE THREAD

**Issue by elfogre** [difi/oxalis#246]
Hello,

I'm Jose Escobar from Edicom. Currently we are testing our AS2 AP against a client that uses your solution and they have a problem validating our MDN responses. Their problem is that they can't extract  Received-content-MIC value. 

Our headers:
------=_Part_4781198_1139735615.1457003702004
Content-Type: message/disposition-notification
Content-Transfer-Encoding: 8bit

Reporting-UA: AS2/AS4 Java Server; Edicom AS2/AS4 Java Server 3.0.1
Original-Recipient: rfc822; APP_1000000097
Final-Recipient: rfc822; APP_1000000097
Original-Message-ID: 3517c913-dd48-430f-a3e6-ccd626dcd8ef
Disposition: automatic-action/MDN-sent-automatically;processed
Received-content-MIC: R4U+uqEUydxnTSMPvA4HhHDh/qM=, sha1

------=_Part_4781198_1139735615.1457003702004--

But your software is expecting "String receivedMic = ret.get("Received-Content-MIC");" it has an uppercase C "Received-**C**ontent-MIC" 

In RFC https://www.ietf.org/rfc/rfc4130.txt Received-content-MIC is specified with a lowercase C as we are sending. 

Could you please change it on your MdnMimeMessageInspector class??

**Comment by steinarcook** [comment]
This is certainly a bug and should be fixed asap. A general rule of thumb; header names should be case insensitive.

**Comment by steinarcook** [comment]
Fixed in 3.2.0 and Release4
