### ISSUE TITLE
For incoming document in peppol the endpoint id value is getting wrongly saved in BD

### ISSUE THREAD

**Issue by 141gaurav** [difi/oxalis#250]
Step to replicate :-
1) Send 1 simpler invoice file without SBDH from oxalis standalone
2) The file is sent successfully
3) The value that Oxalis is saving in the header is NOT correct. Instead of the AccountingCustomerParty.EndpointID it is saving the AccountingCustomerParty.Party.PartyLegalEntity.CompanyID

Here the file "XmlData.xml
[OxalisSampleFile.zip](https://github.com/difi/oxalis/files/258673/OxalisSampleFile.zip)

" is the file which is sent without SBDH and
the file which oxalis creats after adding SBDH header is AddingSBDH.xml

**Comment by 141gaurav** [comment]
Hi,

By when can we expect the fix for this issue.

Thanks,
Gaurav

**Comment by klakegg** [comment]
There are three ways to fix a bug in an open source project:

1. Contribute the fix.
1. Pay someone to contribute the fix.
1. Wait for the maintainers to come around to contribute the fix.

You may consider one of the two first solutions if this is time critical for you. Difi will come around, but not today. It may of course be fixed faster if you provided any information on the version used for reproduction of the bug.

Also this is tagged "major bug", but it is not equivalent to A-bug. The bug does not exist if you choose to add the outer SBDH to the BD before sending using Oxalis, so it is more of a C- or B-bug.

**Comment by steinarcook** [comment]
I am unable to recreate this bug. Which version of Oxalis are you using? Are you overriding any of the properties for outbound messages?

**Comment by 141gaurav** [comment]
I am using Oxalis 3.1.1 version. No I am not.

**Comment by steinarcook** [comment]
Have you tried version 3.2? I am not able to recreate this issue in "release4", which uses more or less the same code base as 3.2.
