### ISSUE TITLE
Include X-Frame-Options response header when returning HTML content (webapp)

### ISSUE THREAD

**Issue by hmspider** [difi/oxalis#251]
In order to avoid potential clickjacking vulnerability (low risk)
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet

**Comment by klakegg** [comment]
Oxalis is an application supporting machine-to-machine interaction. Frames is a functionality in browsers to support human-to-machine interaction. I can't think of any use case where putting the Oxalis web interface into a frame may trigger any security implications. Could you please provide such an use case (here or directly to me)?

Rather than having Oxalis (and maybe other m2m applications) support and maintain such an response header, it may be better to have the reverse proxy inject any response headers of choice?

**Comment by steinarcook** [comment]
According to [Owasp](https://www.owasp.org/index.php/Clickjacking):

_Clickjacking, also known as a "UI redress attack", is when an attacker uses multiple transparent or opaque layers to trick a user into clicking on a button or link on another page when they were intending to click on the the top level page._

Oxalis does not provide a user interface (UI), only an Application Programming Interface (API). As such I don't understand this issue. 

Kindly elaborate why this is an issue :-)

**Comment by hmspider** [comment]
Espap IT Ops Sec Team performed a security audit on our installation of Oxalis. The automated test tool spitted out a report mentioning said clickjacking vulnerability.

The security report does not mention a specific endpoint. From my limited understanding of the code, the welcome page returned by [oxalis-inbound/src/main/webapp/index.jsp] (oxalis-inbound/src/main/webapp/index.jsp) is the only html content (UI) returned by Oxalis; So In theory it could be clickjacked.

The tool offered pointers for further investigation on the reported vulnerability, which I took upon myself to study. There is stated the threat level assessed automatically can/shoud be balanced with the nature (ie sensitiveness) of the info presented in the page. If said info is non-sensitive they go to the extent of affirming a test result can be regarded as false positive.

Two suggestions were presented to Espap IT Ops Sec Team: (1) inject recommended response header in the reverse proxy and (2) reassess the threat level based on the security-neutral content of the page and hence the possibility of a false positive previous result. 

At the same time this Github issue was opened on the assumption that Difi, as the maintainer of Oxalis, would know how to interpret the results better than anyone, and take any action if deemed necessary.

**Comment by klakegg** [comment]
No action deemed necessary.
