### ISSUE TITLE
Oxalis REST API feature

### ISSUE THREAD

**Issue by aleksandrov** [difi/oxalis#252]
It is not an issue, it is about a new feature! :-)

It will be cool to have some REST API to send document out of the box instead of command-line tool usage. It also make sense to have API to GET received documents as well.

Is it in scope of Oxalis?

**Comment by pr0nin** [comment]
If I understand the feature request correctly this would be very welcomed. Especially for us running Oxalis in a .net environment.

**Comment by steinarcook** [comment]
We are working on this and hope to make a REST interface available real
soon.

The API is documented here: https://ap.unit4.com/rest.html

The API will be augmented with functionality to allow handling of ASiC and
REM evidence :-)

On 25 May 2016 at 15:01, Johan Grønstad <notifications@github.com> wrote:

> If I understand the feature request correctly this would be very welcomed.
> Especially for us running Oxalis in a .net environment.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/difi/oxalis/issues/252#issuecomment-221568419>
>



-- 
Steinar Overbeck Cook

**Comment by aleksandrov** [comment]
Thats really cool to get positive feedback so fast! Is it planned to release that as a part of original Oxalis distribution here? 

Thank you guys!

**Comment by steinarcook** [comment]
We have not decided on packaging yet. I think we might publish "vefa-rest" as a separate component. 

Steinar Overbeck Cook
+47 90665793

**Comment by klakegg** [comment]
https://github.com/difi/vefa-srest is alive.

Inclusion of REST interface Oxalis is currently not on the roadmap as this outside scope of the project.
