### ISSUE TITLE
Binary releases outdated?

### ISSUE THREAD

**Issue by jannewaren** [difi/oxalis#254]
Hello!

It says in README.md:

> Binary distributions are available at [Difi](http://vefa.difi.no/oxalis/).

These binary artifacts seem to be outdated. I would want to get oxalis-distribution-3.2.0 but there's only RC1 and SNAPSHOT available. Why no actual releases?

The SNAPSHOT seems to be dated at 03-Nov-2015 19:11 and RC1 at 16-Mar-2016 09:29 - but still there are changes in the oxalis-3.2.0 tag from this month.

Can you update the binary artifacts please? Thank you!

**Comment by klakegg** [comment]
Fixed.
