### ISSUE TITLE
Date format in PeppolMessageMetaData

### ISSUE THREAD

**Issue by monze** [difi/oxalis#256]
Hey

We are a C# based company, that is using the Oxalis AccessPoint. When we receive a document from Oxalis, it is stored in the inbound directory, beside the PeppolMessageMetaData file.

In the PeppolMessageMetaData file, the actually receiving timestamp is 'sendersTimeStamp'/'receivedTimeStamp'. However, this timestamp is in Java default format, and is quite hard (impossible) to parse in the C# environment. Could the format of the timestamp, be included in the 'oxalis-global.properties' file? If no format exist in the 'oxalis-global.properties', the Java default should be used.
In C# the format of the date is based on the language, the current thread is running, and there is no (to my knolege) standard way in C# of parsing the time zone (CET, UCT, ect.) to a known timezone.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by teedjay** [comment]
If you look at oxalis-commons and SimpleMessageRepository.java file you will see how the JSON was built.  

```
sb.append(createJsonPair("receivedTimeStamp", headers.getReceivedTimeStamp()));
```

If you replace this with the code below you'll get ISO8601 formatted dates that should be easy to parse.

```
Date date = headers.getReceivedTimeStamp();
LocalDateTime ldt = LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
sb.append(createJsonPair("receivedTimeStamp", dt.toString()));
```

**Comment by klakegg** [comment]
Timestamps represented using RFC 1123 is not problematic to parse according to Google.

**Comment by monze** [comment]
First, I'm quite dissatpointet. Everyone can use google, but without understanding the problem, you can't expect to find a valid result.

Problem: We are a C# house, and if you use Google, you notise, that the list of time zone used in standard Java, is not implemented in C#. So we can't parse the current format, without implementing the list our self. This is NOT a valid solution.

Big problem: If you use google, you notice, that the format of the date, is not unique, as this example will shows - Note, the problem is the TimeZone, not the parsing of year, month or day.
First my simple test code. Notice, that we just print a date object to the console, just like the code in Oxalis, print the date object to the StringBuilder
```
public class testone {
    public static void main(String[] args) {
        Date date = new Date();
        System.out.println("The date is: " + date); // Display the string.
    }
}
```

If you set your windows timezone to Central America -06:00, and you will get this out

Fri Jul 01 00:52:26 CST 2016 

If you set your windows timezone to Beijing, Chongqing, Hong Kong, Urumqi +08:00, you will the this output

Fri Jul 01 14:52:26 CST 2016

We now have a two different result, that can't uniquely be parsed back into one date + TimeZone. We don't know which timezone to select. If is a fine human readable timestamp, but not a machine readable timestamp.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by steinarcook** [comment]
Can you parse ISO8601 time stamps (with time zone)?

Steinar Overbeck Cook
+47 90665793

**Comment by monze** [comment]
Yes, we can parse the ISO8601 time stamps (with time zone).
If we look at https://en.wikipedia.org/wiki/ISO_8601, there is several formats of the format including time zone.
Preferably the result should look something like this:
2016-07-04T15:18:24+00:00
2016-07-04T16:18:24+01:00
That timestamp can be parsed in all program languages.

But, I would prefer, that the format of the timestamp, should be defined in the 'oxalis-global.properties'. If format exist in the file, the current format is used. That way, the output of Oxalis is backward compatible, and if any have special request to the format, it can easily be modified to their needs.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
We will look into this when we receive a pull request.
