### ISSUE TITLE
Date format in PeppolMessageMetaData

### ISSUE THREAD

**Issue by monze** [difi/oxalis#257]
Se issue 256

We are a C# based company, that is using the Oxalis AccessPoint. When we receive a document from Oxalis, it is stored in the inbound directory, beside the PeppolMessageMetaData file.

In the PeppolMessageMetaData file, the actually receiving timestamp is 'sendersTimeStamp'/'receivedTimeStamp'. However, this timestamp is in Java default format, and is quite hard (impossible) to parse in the C# environment. Could the format of the timestamp, be included in the 'oxalis-global.properties' file? If no format exist in the 'oxalis-global.properties', the Java default should be used.
In C# the format of the date is based on the language, the current thread is running, and there is no (to my knolege) standard way in C# of parsing the time zone (CET, UCT, ect.) to a known timezone.

Jacob Mogensen
mySupply ApS
Denmark

---------------------
Adding an example, just for reference.
{ "PeppolMessageMetaData" :
  {
    "messageId" : "ae25bd0d-0cf7-47eb-890f-f45e549abbef",
    "recipientId" : "9908:810418052",
    "recipientSchemeId" : "NO:ORGNR",
    "senderId" : "9908:923232206",
    "senderSchemeId" : "NO:ORGNR",
    "documentTypeIdentifier" : "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol4a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0::2.1",
    "profileTypeIdentifier" : "urn:www.cenbii.eu:profile:bii05:ver2.0",
    "sendingAccessPoint" : "APP_1000000081",
    "receivingAccessPoint" : "APP_1000000119",
    "protocol" : "AS2",
    "userAgent" : null,
    "userAgentVersion" : null,
    "sendersTimeStamp" : null,
    "receivedTimeStamp" : "Thu Jun 09 16:20:26 CEST 2016",
    "sendingAccessPointPrincipal" : "O=Data Interchange Plc,CN=APP_1000000081,C=UK",
    "transmissionId" : "8a2beb44-2d3f-4101-91e1-58b04ef19fb9@APP_1000000081",
    "buildUser" : "${env.USER}",
    "buildDescription" : "oxalis-4.0.0-RC1-0-g937e92e",
    "buildTimeStamp" : "24.05.2016 @ 20:32:28 CEST",
    "oxalis" : "4.0.0-RC1"
  }
}
teedjay

---------------------------
If you look at oxalis-commons and SimpleMessageRepository.java file you will see how the JSON was built.

sb.append(createJsonPair("receivedTimeStamp", headers.getReceivedTimeStamp()));
If you replace this with the code below you'll get ISO8601 formatted dates that should be easy to parse.

Date date = headers.getReceivedTimeStamp();
LocalDateTime ldt = LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
sb.append(createJsonPair("receivedTimeStamp", dt.toString()));

teedjay

----------------------
Problem: We are a C# house, and if you use Google, you notise, that the list of time zone used in standard Java, is not implemented in C#. So we can't parse the current format, without implementing the list our self. This is NOT a valid solution.

Big problem: If you use google, you notice, that the format of the date, is not unique, as this example will shows - Note, the problem is the TimeZone, not the parsing of year, month or day.
First my simple test code. Notice, that we just print a date object to the console, just like the code in Oxalis, print the date object to the StringBuilder
```
public class testone {
    public static void main(String[] args) {
        Date date = new Date();
        System.out.println("The date is: " + date); // Display the string.
    }
}
```
If you set your windows timezone to Central America -06:00, and you will get this out

Fri Jul 01 00:52:26 CST 2016

If you set your windows timezone to Beijing, Chongqing, Hong Kong, Urumqi +08:00, you will the this output

Fri Jul 01 14:52:26 CST 2016

We now have a two different result, that can't uniquely be parsed back into one date + TimeZone. We don't know which timezone to select. If is a fine human readable timestamp, but not a machine readable timestamp.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
You are free to provide your own implementation of the MessageRepository.
