### ISSUE TITLE
Not possible to set timeouts for As2MessageSender

### ISSUE THREAD

**Issue by kdkanishka** [difi/oxalis#258]
I wanted to set a default timeout for the AS2 communication, After looking at the code, I realized timeout is not configurable for AS2 sender. 
I have done a fix for this and planning to do a pull request.

**Comment by steinarcook** [comment]
Thank you. We are looking forward to see your contribution :-)

**Comment by kdkanishka** [comment]
Thanks for accepting the issue. I have done a pull request. :)
