### ISSUE TITLE
Oxalis AS2 implementation comply with FIPS 140-2?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#262]
I understand that Oxalis AS2 implementation is custom one. I want to know whether Oxalis AS2 implementation comply with FIPS 140-2 standard?

**Comment by aaron-kumar** [comment]
Can I know which Cryptographic algorithms is used for Oxalis As2 implementation?

**Comment by klakegg** [comment]
Oxalis is implemented according to the PEPPOL AS2 profile.
