### ISSUE TITLE
very minor documentation issue (location of oxalis-global.properties in distribution)

### ISSUE THREAD

**Issue by tjeb** [difi/oxalis#263]
Hi,

I just had a user with the issue that the installation step where oxalis-global.properties is copied failed for him; the documentation says to copy it from /target, whereas in the distribution it is put into etc/. Nothing big and pretty easy to find, but for correctness it would be nice to mention it :)

Jelte

**Comment by tjeb** [comment]
also, a number of links in the main readme.md (such as the installation guide) don't appear to work when viewed in github

**Comment by steinarcook** [comment]
Aha, thanks! Will fix

**Comment by steinarcook** [comment]
Just checked the links to the installation guide, seems to work fine. Can you be more explicit?

**Comment by tjeb** [comment]
huh, one example was that 'See the installation guide for more additional details' linked to https://github.com/doc/install/installation.md but it seems ok now. Perhaps there was a temporary failure in githubs markdown links generator or something. So never mind :)

**Comment by steinarcook** [comment]
Ok :-) Seems to be ok now, closing it and we can re-open if there broken links.
