### ISSUE TITLE
Query on handling the Inbound Documents via Peppol

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#268]
Hi All,

We are using the following version of Oxalis, : https://peppolap.everbinding.nl/as2

version.oxalis: 3.0.2-SNAPSHOT
version.java: 1.7.0_51
oxalis.operation.mode: PRODUCTION
oxalis.pki.version: V2
oxalis.sml.hostname: edelivery.tech.ec.europa.eu
certificate.subject: O=eConnect International B.V.,CN=APP_1000000187,C=NL
certificate.issuer: CN=PEPPOL ACCESS POINT CA,O=NATIONAL IT AND TELECOM AGENCY,C=DK
certificate.expired: false
build.id: ${git.commit.id}
build.tstamp: ${git.commit.time}

and Inbound and Outbound is working fine for us.

**Now the questions is,

1. One of the SI members was able to send a document via PEPPOL to us only using a self signed certificate. Is it a security vulnerability? If yes Where can we handle this in Oxalis level ?**

Thanks in Advance,
VijayaKumar

**Comment by steinarcook** [comment]
Your Oxalis installation is outdated. You should at least use a final build, i.e. not a "SNAPSHOT" version.

I urge you to update to the latest version as several security holes have been fixed.

**Comment by VijayaKumar2** [comment]
Hi,

Which version should we need to update, since we are in production
environment now, Is there any impact for these upgrade ?


Thanks,
Vijay
