### ISSUE TITLE
Do we have Test SMP ???

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#275]
Hi,

Currently we are having one access point in SMP which is used for our production environment for everbinding. So now we are setting up our test acceptance environment where our component will run in Test mode with different access point.

Now the problem is, if the company A is already registered in production environment access point to SMP, if the same company A is again registered with test access point, what will be the impact, it will affect the existing production environment access point right ?

Do we have some Test SMP - Galaxy URL kind of thing which can be used for these kind of testing purpose?

Please help us as soon as possible.

Thanks,
Vijay

**Comment by klakegg** [comment]
This issue is not related to the source code of Oxalis.

**Comment by VijayaKumar2** [comment]
Yes.. You are right, there are no issues w.r.t source code.

Is it possible to have test SMP registration without disturbing the production ?

**Comment by klakegg** [comment]
This issue is not related to the source code of Oxalis.
