### ISSUE TITLE
Good to have authenticated access to access statistics

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#281]
This is what written in Oxalis readme file:
oxalis/statistics 	RAW statistics for DIFI 	HTTPS with proper certificates 	Used by DIFI to collect statistics

Statistics URL is suspected to attack. Though it generate encrypted statistics report which only DIFI can open but still everyone can run execute that query provide AP url is known. 

Query with granularity=Y is heavy query and should be placed inside authenticated access. AP can share authentication details with DIFI.

**Comment by klakegg** [comment]
Statistics is turned off by default in Oxalis 4.0.0.
