### ISSUE TITLE
Selfsigned certificate allowed in inbound AS2 (4.0.0-RC1)

### ISSUE THREAD

**Issue by PeterOlausson65** [difi/oxalis#282]
I'm testing the PEPPOL AP compliance using Oxalis 4.0.0-RC1 and noticed that there is no validation of the signers certificate? I setup the server in PRODUCTION mode and it accepted messages signed with a self-signed certificate.

Adding the following lines to eu.peppol.as2.InboundMessageReceiver.java would fix this security issue

            MimeMessage mimeMessage = MimeMessageHelper.createMimeMessageAssistedByHeaders(inputStream, httpHeaders);
            SignedMimeMessage signedMimeMessage = new SignedMimeMessage(mimeMessage);
            // Validate the signer certificate
            if(!this.oxalisCertificateValidator.validate(signedMimeMessage.getSignersX509Certificate())) {
                throw new InvalidAs2MessageException("The signers certificate is not a valid PEPPOL certificate");
            }

**Comment by klakegg** [comment]
This is fixed as of 4.0.0-RC2
