### ISSUE TITLE
Access to AP specific server details - All  AS2 (POST & GET) request should always go through access control via certificate

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#285]
All the POST requests should always go through access control (certificate based authentication) and return 401 if not authorized

GET response is totally useless and should not be returned. We should not return any “OK” responses, given that the request is not authorized (and this is easy to change, just remove the GET support from code)

Following details is being revealed: 
As2-Version: 1.0
Connection: keep-alive
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; boundary="----=_Part_4590450_986497720.1488811445283"
Date: Mon, 06 Mar 2017 14:44:05 GMT
Message-Id: <292037236.4590451.1488811445283.JavaMail.root@SERVER_NAME>
Mime-Version: 1.0
Server: Oxalis
Set-Cookie: AWSALB=YIAM1iM0l6E3OkVm3AVV+mcOZfdn+hXy4Y/C0geTZoqi7SL20SmRZeIkq+i3Ue+he8rsyj6PR2dgjrsYTNw+CZxgIglc1UjWJN9+oN/Oi6yZeu7Q6v5odbaGZeSN; Expires=Mon, 13 Mar 2017 14:44:05 GMT; Path=/
Subject: AS2 MDN as you requested
Transfer-Encoding: chunked

**Comment by klakegg** [comment]
In which standard may I find information regarding this?
