### ISSUE TITLE
Oxalis-distribution missing after building

### ISSUE THREAD

**Issue by Marcv89** [difi/oxalis#289]
I'm trying to build Oxalis myself with Maven; first 'mvn compile' then 'mvn install -DskipTests'. I get a 'BUILD SUCCES' twice, but only in oxalis-distribution the 'target' folder is missing. All other folders have a 'target' folder'. Why is it missing in oxalis-distribution?

**Comment by klakegg** [comment]
Deistribution artifacts are no longer created automatically. Make sure to trigger build with the "dist" profile to create also distribution artifacts.
