### ISSUE TITLE
Too many connections from Mysql while sending the document via Oxalis -

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#290]
Hi,

we are getting the following exception, when we are sending the document via PEPPOL with oxalis,

Now we have increased the MAX_CONNECTION setting in mysql server.

The question is, do we need to change/follow some standard in the code level to avoid this kind of issues in future.
Can any one help us regarding this.

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: \"Too many connections\"\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat com.mysql.jdbc.Util.handleNewInstance(Util.java:411)\n\tat com.mysql.jdbc.Util.getInstance(Util.java:386)\n\tat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)\n\tat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)\n\tat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)\n\tat com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1112)\n\tat com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2483)\n\tat com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2516)\n\tat com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2301)\n\tat com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:834)\n\tat com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:47)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat com.mysql.jdbc.Util.handleNewInstance(Util.java:411)\n\tat com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)\n\tat com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:346)\n\tat

**Comment by klakegg** [comment]
Answered in #292.
