### ISSUE TITLE
Message-ID customization

### ISSUE THREAD

**Issue by intesa-oxalis** [difi/oxalis#294]
Hi, we are working with oxalis 4.0.0-RC3-SNAPSHOT.
We would like to customize the Message-ID: which is the correct way to do this?

**Comment by mindweaver** [comment]
Same here. Is there some way to specify the Message-ID (filename) when sending with the standalone.jar?

**Comment by hjkjorstad** [comment]
Same here. We would also like a way of customize these message - and/or transmission id's.
Now we have a format like this with oxalis 4.0.0 : transmissionId='<468922153.4691.1526013659845.JavaMail.**user@host**>'

**Comment by intesa-oxalis** [comment]
Sono fuori dall'ufficio fino a 30/08/2018

Risponderò al messaggio al mio ritorno.





Nota: Questa è una risposta automatizzata al messaggio  "Re: [difi/oxalis]
Message-ID customization (#294)" inviata il 21/08/2018 21:40:07.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
