### ISSUE TITLE
oxalis-statistics in oxalis-inbound

### ISSUE THREAD

**Issue by intesa-oxalis** [difi/oxalis#295]
Hi, we are working with oxalis 4.0.0-RC3-SNAPSHOT.
We would like to integrate oxalis-statistics with oxalis-inbound (if it's possible), but when we add statistics dependecy in the inbound pom.xml a circular dipendency error is rised.
Which is the correct way to use statistics in inbound?

**Comment by klakegg** [comment]
You are supposed to handle your own dependencies in your own project, not changing dependencies within Oxalis.
