### ISSUE TITLE
Is there way to set throttle limit for traffic coming from partcular AP ?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#296]
Currently there is no way to set throttle limit for traffic coming from particular AP. 

One possibility to set throttle limit is in  load balancer and SSL offloader (e.g Apache or Nginx etc) . But that will be for whole PEPPOL traffic instead to one specific AP.

Do Oxalis offer someway to deal with it?

**Comment by klakegg** [comment]
This is out of scope for the Oxalis project.
