### ISSUE TITLE
documentation oxalis 4+ still refers to oxalis-global.properties on to many places

### ISSUE THREAD

**Issue by Brummos** [difi/oxalis#299]
The documentation at the moment is a big mess. A lot of the documentation for oxalis 4+ is still refering to oxalis-global.properties while this should be oxalis.conf?

example: oxalis source > developer-readme.md

this is just 1 example. 

and this is not the only thing that is refering to old versions.

any chance we can have a proper update on the documentation?

**Comment by pschoond** [comment]
Totally agree. Took me hours/days to find this one...
