### ISSUE TITLE
oxalis.conf cannot be found within the sources

### ISSUE THREAD

**Issue by Brummos** [difi/oxalis#300]
the installation guide on "https://github.com/difi/oxalis/blob/master/doc/install/installation.md"

says the following
Copy and edit the file oxalis.conf. Here is an example of how it might look:

but oxalis.conf cannot be found within the oxalis source?

where can i find this?

**Comment by pschoond** [comment]
There is none, I constructed my own. Found this which explains some. I think syntax is basically the same: https://github.com/difi/oxalis/blob/master/doc/configuration.adoc

For what it's worth, this is mine:
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=oxalis-keystore.jks
     password=peppol
     key.alias=test
     key.password=peppol
 }
 
 # The relative name of the directory holding plugin
# oxalis.path.plugin = oxalis-plugin
oxalis.path.plugin = ../oxalis/bin \# not sure what this is
 
 # Signals to Oxalis that we should look for plugin
 oxalis.persister.receipt = plugin
 
 # Where to store inbound files
 oxalis.path.inbound = /data/peppol/IN

 # logfile 
oxalis.logging.config = logback-oxalis.xml

# Mode of operation? Specify TEST for pilot/test certificate or PRODUCTION for production (defaults to TEST)
oxalis.operation.mode=TEST

**Comment by Brummos** [comment]
thank you so much for this

**Comment by pschoond** [comment]
Hope it works for you. It still wont start for me (issue \#297)
Let me know

**Comment by Brummos** [comment]
it helped a bit, i'm on the same error as you have (issue #297) now :)

**Comment by pschoond** [comment]
So now I hope it's not in the conf file.

Small update to \#297 (same error)
