### ISSUE TITLE
sending invoice to yourself - i is not a recognized option

### ISSUE THREAD

**Issue by mikecgthb** [difi/oxalis#301]
We completed installation steps and successfully sent a sample invoice to Difi's test access point but when we tried to send a sample invoice to our own access point, we got "*** i is not a recognized option".

We tried both, one in installation.md file "java -jar target/oxalis-standalone.jar -f src/main/resources/BII04_T10_PEPPOL-v2.0_invoice.xml -r 9908:810418052 -s 9946:ESPAP -u http://localhost:8080/oxalis/as2 -m as2 -i APP_1000000xxx" and one we found in example.sh "java -jar target/oxalis-standalone.jar -f ./src/test/resources/BII04_T10_PEPPOL-v2.0_invoice.xml -r 9908:810418052 -s 9908:810017902 -u https://localhost:8080/oxalis/as2 -m as2 -id APP_1000000xxx"

one of them has -i and example.sh has -id but we get same error for both.

What are we missing here?

**Comment by mmnclk** [comment]
It looks like -i changed with version 4. when I look at main.class, I see that we need to use -cert instead. but when I do, I get "Exception in thread "main" no.difi.certvalidator.api.CertificateValidationException: Could not parse certificate: java.io.IOException: Empty input" error message. I use my jks file as cert. my certificate looks fine. I can send invoices to Difi. I use it like -cert /path/to/my/cert . 

can anyone help me to figure this out please?

**Comment by QAnders** [comment]
Did you figure this one out?
I get the same error...

**Comment by mikecgthb** [comment]
yes, -i & -m no longer in use. try: java -jar target/oxalis-standalone.jar -f your_invoice_file.xml -r 9908:810418052 -s 9946:ESPAP -u http://localhost:8080/oxalis/as2 -cert your_openpeppol_certificate.cer

**Comment by QAnders** [comment]
Awesome, thanks!
That works better!

A question though, how can I set sending and receiving AP?
Sender and receiver (AS2-To and AS2-From) is now the same, taken from the cert which then faults in our gateway as `automatic-action/mdn-sent-automatically;processed/error: sender-equals-receiver`

**Comment by klakegg** [comment]
The PEPPOL AS2 specification specifies the AS2-To and AS2-From to contain the CN from the PEPPOL certificate, thus are there no reason to make it possible to override this in Oxalis.

**Comment by QAnders** [comment]
Ah, I understand and see the logic.

Using the public key of another AP thus gives me separate but AS2-To and AS2-From but then I get a verification error in Oxalis standalone as it is trying to find my certificate in SMP (but we are not yet registered as we are in Testing phase):

```
2018-05-18 11:23:41,341 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Certificate in MDN ('CN=APP_1000000xxx,O=Some Company AB,C=SE') does not match certificate from SMP ('CN=APP_2000000xxx,O=DIFI,C=NO').
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Certificate in MDN ('CN=APP_1000000xxx,O=Some Company Group AB,C=SE') does not match certificate from SMP ('CN=APP_2000000xxx,O=DIFI,C=NO').
```

Might be considered for some future fix/feature to make it possible to add certificates for both sender and receiver so one can "fake" being an external AP for testing purposes?
