### ISSUE TITLE
Oxalis 4.0 RC2 asks for oxalis-global.properties

### ISSUE THREAD

**Issue by bjornhellem** [difi/oxalis#304]
Hi,

We have installed Oxalis Inboud on Tomcat 9.0 with java version 1.8.0_45. Deployed oxalis.war from precompiled version from: https://search.maven.org/#search%7Cga%7C1%7Coxalis

The archive we used was file: 
oxalis-inbound | 4.0.0-RC2  all (6) | 01-Mar-2017

We deployed the file from path inside archive: oxalis-distribution-latest -> j2ee -> oxalis.war throug manager in tomcat.

I can see from documentation that oxalis.conf should replace the need for oxalis-global.properties, however, when trying to start oxalis it fails with the following message:
12:31:18.582 [main] INFO eu.peppol.util.OxalisHomeDirectory - Attempting to locate home dir ....
12:31:18.593 [main] INFO eu.peppol.util.OxalisHomeDirectory - Unable to locate JNDI path java:comp/env/OXALIS_HOME
12:31:18.594 [main] INFO eu.peppol.util.OxalisHomeDirectory - Using OXALIS_HOME specified as Environment Variable $OXALIS_HOME as /usr/apache-tomcat-9.0.1/oxalis_home
12:31:18.594 [main] INFO eu.peppol.util.GlobalConfigurationImpl - Oxalis home directory: /usr/apache-tomcat-9.0.1/oxalis_home
12:31:18.596 [main] DEBUG eu.peppol.util.GlobalConfigurationImpl - Loading configuration properties from /usr/apache-tomcat-9.0.1/oxalis_home/oxalis-global.properties
12:31:18.596 [main] ERROR eu.peppol.util.GlobalConfigurationImpl - Unable to load the Oxalis global configuration from /usr/apache-tomcat-9.0.1/oxalis_home/oxalis-global.properties
09-Nov-2017 12:31:18.599 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
09-Nov-2017 12:31:18.600 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/oxalis] startup failed due to previous errors

When adding an oxalis-global.properties file in $OXALIS_HOME folder, this message goes away, and it looks like it is stopping on key/trust related errors, which I assume we will be able to solve. 

So the question is, should we use oxalis.conf or oxalis-global.properties. If oxalis.conf should be used, how do we configure it to use oxalis.conf?

Regards, Bjørn Hellem

**Comment by bjornhellem** [comment]
Anybody experiencing this and possibly has a solution?

**Comment by klakegg** [comment]
The log does not look like Oxalis 4.0 RC2.
