### ISSUE TITLE
Connection struck during SSL Handshake, Is connection timeout set in Oxalis for outbound traffic?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#305]
Is there any connection timeout set in As2MessageSender while sending document to PEPPOL network? 
I did not found one in oxalis version that we are using.

Problem happen during SSL handshake 
>>Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]  (SSLConnectionSocketFactory.java:388) 
DEBUG [SimpleAsyncTaskExecutor-1] 11-09 21:27:23 Enabled cipher suites:[*ciper-suites-list*]  (SSLConnectionSocketFactory.java:389) 
DEBUG [SimpleAsyncTaskExecutor-1] 11-09 21:27:23 Starting handshake  (SSLConnectionSocketFactory.java:393) 

Here oxalis keep on waiting for secure session indefinitely..... 

In normal case , after request for handshake, secure connection is established quickly: 
>>DEBUG [SimpleAsyncTaskExecutor-1] 11-09 21:22:05 Starting handshake  (SSLConnectionSocketFactory.java:393) 
DEBUG [SimpleAsyncTaskExecutor-1] 11-09 21:22:05 Secure session established  (SSLConnectionSocketFactory.java:423)

**Comment by aaron-kumar** [comment]
In START protocol, we have some defined properties value for timeout. START protocol is not used now, Can we have similar setting for timeout for AS2 protocol?
>># START : Control HTTP connection timeout in milliseconds when using START protocol
# oxalis.connection.timeout=5000

# START : Control HTTP read timeout in milliseconds when using START protocol
# oxalis.read.timeout=5000

**Comment by klakegg** [comment]
Duplicate of #291.
