### ISSUE TITLE
Oxalis fails during startup due to "Unable to detect mode for certificate"

### ISSUE THREAD

**Issue by bjornhellem** [difi/oxalis#307]
Hi,

We are installing oxalis with a self signed certificate, and oxalis fails during startup with the following error:
5:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - Settings: Persister
15:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => PAYLOAD: default
15:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => RECEIPT: plugin
15:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => HANDLER: default
15:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - Settings: Tracing
15:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => REPORTER: noop
15:55:13.105 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => HTTP: null
15:55:13.106 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - Settings: Statistics
15:55:13.106 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => SERVICE: noop
15:55:13.106 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - Settings: Transmission
15:55:13.107 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => VERIFIER: default
15:55:13.107 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - Settings: Logging
15:55:13.107 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => CONFIG: logback-oxalis.xml
15:55:13.107 [main] INFO no.difi.oxalis.commons.settings.SettingsBuilder - => SERVICE: logback
15:55:13.107 [main] DEBUG no.difi.oxalis.commons.logging.LoggingHandler - Logger config: logback-oxalis.xml
15:55:13.107 [main] INFO no.difi.oxalis.commons.logging.LoggingHandler - Logging service: logback
Configuring Logback with configuration: /usr/tomcat/.oxalis/logback-oxalis.xml
20-Nov-2017 15:55:13.632 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [guiceFilter]
 com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, no.difi.vefa.peppol.common.lang.PeppolLoadingException: Unable to detect mode for certificate 'EMAILADDRESS=xxxx@xxx.no, CN=xxx.no, OU=EHF, O=XXX, L=XXX, ST=XXX, C=NO'.
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
  while locating no.difi.vefa.peppol.mode.Mode
    for the 3rd parameter of no.difi.oxalis.inbound.servlet.StatusServlet.<init>(StatusServlet.java:58)

Why is this? We are not able to see that is reads the parameter oxalis.operation.mode= TEST. Should it list this as a parameter during startup?

Regards, Bjørn

**Comment by klakegg** [comment]
Oxalis 4.0 RC2+ does not recognize `oxalis.operation.mode`. The reported behaviour is according to expectations.

**Comment by bjornhellem** [comment]
Hi, 
Thank for your reply. What does this mean? What do you suggest we do?

Regards, Bjørn

**Comment by klakegg** [comment]
We suggest to use valid OpenPEPPOL AP certificate.

**Comment by ig2503** [comment]
Hi,
we are facing the similar issue while deploying oxalis.war. Our certificate is a valid PEPPOL Test AP certificate:
1) Error in custom provider, no.difi.vefa.peppol.common.lang.PeppolLoadingException: Unable to detect mode for certificate 'C=XX, O=XX, OU=PEPPOL TEST AP, CN=XXX'.
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
  while locating no.difi.vefa.peppol.mode.Mode
    for the 3rd parameter of no.difi.oxalis.inbound.servlet.StatusServlet.<init>(StatusServlet.java:58)
  at no.difi.oxalis.inbound.servlet.StatusServlet.class(StatusServlet.java:58)
  while locating no.difi.oxalis.inbound.servlet.StatusServlet

Why is that happening? How can we solve that issue to start oxalis? How can we specify/define the mode?
Thank you in advance,
IG
