### ISSUE TITLE
Unable to setup oxalis 4

### ISSUE THREAD

**Issue by zonenet** [difi/oxalis#310]
Hello,

I'm trying to install oxalis 4 but I'm unable to properly set it up and deploy it for some reason.

My setup:
Ubuntu 16.04.03
javac 1.8.0_151
Maven 3.3.9

oxalis.conf:
`oxalis.keystore {
     path=oxalis-keystore.jks
     password = myPassword
     key.alias = ap
     key.password = myPassword
 }

oxalis.path.plugin = oxalis-plugin

oxalis.persister.receipt = plugin

oxalis.path.inbound = /var/peppol/IN

oxalis.logging.config = logback-oxalis-server.xml`

I've read through pretty much everything regarding installation guides, also issues here (open and closed)

versions I've tried: 4 RC2, 4 RC3 and 4 RC4 (RC2 pre-compiled others self built) 

the latest version (RC4) seems to screw up usage of OXALIS_HOME
[no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /
[no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /conf

eventhough I've set Environment variable in the tomcat.service file
Environment=OXALIS_HOME=/home/tomcat9/.oxalis

also have manually set: export OXALIS_HOME=/home/tomcat9/.oxalis for the tomcat user

either way I get these errors (catalina.out)
`2017-12-18 13:56:11,211 INFO [no.difi.oxalis.persistence.datasource.DbcpDataSourceProvider] DataSource: jdbc:h2:file:./data/oxalis
2017-12-18 13:56:11,250 INFO [no.difi.oxalis.commons.logging.LoggingHandler] Logging service: logback
Configuring Logback with configuration: /conf/logback-oxalis-server.xml
18-Dec-2017 13:56:15.070 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
18-Dec-2017 13:56:15.080 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/oxalis] startup failed due to previous errors
18-Dec-2017 13:56:15.108 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [oxalis] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application wa$
18-Dec-2017 13:56:15.109 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [oxalis] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. $
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)
18-Dec-2017 13:56:15.120 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/apache-tomcat-9.0.1/webapps/oxalis.war] has finished in [8,213] ms`

and (oxalis.log)
`2017-12-18 13:56:11,320 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] Prioritized list of transport profiles:
2017-12-18 13:56:11,320 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0r1
2017-12-18 13:56:11,320 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0
2017-12-18 13:56:13,117 INFO [no.difi.oxalis.commons.mode.ModeModule] [] Detected mode: TEST
2017-12-18 13:56:15,054 DEBUG [no.difi.oxalis.persistence.aop.JdbcTxManagerImpl] [] Trace 0:    >>      Unable to get a connection from the provided datasource
2017-12-18 13:56:15,054 DEBUG [no.difi.oxalis.persistence.aop.JdbcTxManagerImpl] [] Trace 0:    >>      Removing transaction manager`

From reading through the issues posted earlier
https://github.com/difi/oxalis/issues/284
stating the need for a database is not nesessary

and
https://github.com/difi/oxalis/issues/297
giving a solution to downgrade java, but thread starter there stating that this didn't work either.

Nevertheless it looks like you need to configure a database or am I wrong?

can anyone verify usage of java v1.8 u151?

**Comment by zonenet** [comment]
Turns out I needed to add
`oxalis.database.datasource = dbcp
oxalis.database.jdbc.connection = "jdbc:h2:file:/home/tomcat9/.oxalis/data/oxalis"`

to my oxalis.conf file.

and "" around the value of jdbc.connection was super important.

now it's only the OXALIS_HOME variable which is not read for some reason..

**Comment by zonenet** [comment]
Fixed it with adding
WorkingDirectory=/my/dir

in my tomcat.service file under [Service]

**Comment by ajaysodhi** [comment]
I recently setup Oxalis 4.0.2 Release on Tomcat 9.  I was facing lots of errors as you guys are facing. Found solution, hope will help you as well who are still struggling for the setup.

**Prerequisites:**
1.  Java 8 (Any version)
2.  Tomcat 9

**Steps to run the oxalis build:**

1.  Download the latest 4.0.2 release from https://github.com/difi/oxalis/releases/tag/oxalis-4.0.2
2.  Build the war using command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdist
3.  go to target at location: oxalis-oxalis-4.0.2\target\distribution\jee\oxalis.war
4.  Deploy that war in tomcat 9.
5.  It will show you errors like mentioned above (apache is stopped already)
6.  Copy **guava-26.0-jre.jar** and **guava-r438.jar** in tomcat 9/lib folder.
7.  Clear tomcat9/work/* folder
8.  Restart tomcat. Oxalis will be up and running.
