### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by kivanceren** [difi/oxalis#311]
Hi, I've tried to install Oxalis on both Linux and Windows machine. But end of the installation, in Tomcat Oxalis folder, I don't have any folder or status file or something like that (except META_INF and WEB_INF). What should be the main reason ?

**Comment by kivanceren** [comment]
Hi, when i've submitted the previous issue, i obtained *.war file with 
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdist command. But whe n i tried to install with mvn clean install, i get error message for oxalis 4.0.0.-RC2 every time. But i don't get at RC2 and RC3. Moreover, after builded oxalis RC2 and RC3 (and master branch, which is RC4) i didn't get any *.war file. 

For RC2 when i try to build project, i'm getting error like this:

eu.peppol.security.x509.CertificateTest
loadCertificate
java.security.cert.CertificateExpiredException: NotAfter: Sun Apr 23 02:59:59 GMT+03:00 2017
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
	at eu.peppol.security.x509.CertificateTest.loadCertificate(CertificateTest.java:74)
... Removed 29 stack frames

If somebody helps me, i will be very pleased.

**Comment by klakegg** [comment]
Expired certificates are not supported.
