### ISSUE TITLE
Sending a sample invoice to Difi's test access point - error

### ISSUE THREAD

**Issue by peppol-test** [difi/oxalis#312]
Command ran 
```
java -jar target/oxalis-standalone.jar \
     -f src/main/resources/BII04_T10_PEPPOL-v2.0_invoice.xml \
     -r 9908:810418052 \
     -s 9909:810418052
``` 
after install oxalis.
Display the following error:

> 1) Error in custom provider, no.difi.oxalis.api.lang.OxalisLoadingException: Unable to load security settings due to lacking certificate. Is configuration correct?
>   at no.difi.oxalis.commons.security.CertificateModule.getCertificate(CertificateModule.java:74)
>   at no.difi.oxalis.commons.security.CertificateModule.getCertificate(CertificateModule.java:74)
>   while locating java.security.cert.X509Certificate
>     for the 1st parameter of no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
>   at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
>   while locating no.difi.vefa.peppol.mode.Mode
>     for the 1st parameter of no.difi.oxalis.outbound.lookup.LookupModule.getLookupService(LookupModule.java:59)
>   at no.difi.oxalis.outbound.lookup.LookupModule.getLookupService(LookupModule.java:59)
>   while locating no.difi.oxalis.api.lookup.LookupService
>     for the 4th parameter of no.difi.oxalis.outbound.transmission.DefaultTransmitter.<init>(DefaultTransmitter.java:67)
>   while locating no.difi.oxalis.outbound.transmission.DefaultTransmitter
>   at no.difi.oxalis.outbound.transmission.TransmissionModule.configure(TransmissionModule.java:47)
>   while locating no.difi.oxalis.api.outbound.Transmitter

The configuration read from the conf file:

> [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /opt/oxalis/conf/oxalis.conf 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Timestamp 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: system 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Evidence 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: rem 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: HTTP 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_TOTAL: 20 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_MAX_ROUTE: 2 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_CONNECT: 0 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_READ: 0 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: File system 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => CONF: conf 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => INBOUND: /var/peppol/IN 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => PLUGIN: oxalis-plugin 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Key store 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => PATH: oxalis-keystore.jks 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => PASSWORD: peppol 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_ALIAS: ap 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_PASSWORD: peppol 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Persister 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => PAYLOAD: default 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => RECEIPT: plugin 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => HANDLER: default 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tracing 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => REPORTER: noop 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => HTTP: null 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Statistics 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: noop 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transmission 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => VERIFIER: default 
> [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Logging 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => CONFIG: null 
> [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: logback

**Comment by peppol-test** [comment]
The Test certificate was received from Peppol. The latest version is installed oxalis.

**Comment by klakegg** [comment]
> Error in custom provider, no.difi.oxalis.api.lang.OxalisLoadingException: **Unable to load security settings due to lacking certificate. Is configuration correct?**

The message from the software is lack of certificate.
