### ISSUE TITLE
Is something missing in Oxalis.war?

### ISSUE THREAD

**Issue by jangj** [difi/oxalis#318]
We have pretty much tried everything
Compiling Oxalis our self and tried the pre-compiled one. Different versions of Java and Tomcat
Tried to install on a clean machine etc

We always get errors like there is something missing
Could not load [no/difi/oxalis/commons/settings/SettingsBuilder.class]

Could not load [com.google.common.util.concurrent.AbstractFuture$Failure$1]

I see others on this forum also has this problem
Is there any solution to this? Is the documentation missing something?

Mvh
Jan Gøytil Jakobsen, Compello

**Comment by klakegg** [comment]
Is this the same as #316?

**Comment by klakegg** [comment]
No response in more than 5 days - closed.

**Comment by jangj** [comment]
ops, sorry I missed your comment
Yes, it seems related to #316

**Comment by jangj** [comment]
We got it to work by moving guava-26.0-jre.jar from webapps\oxalis\WEB-INF\lib to apache-tomcat-9.0.4\lib

**Comment by cook32** [comment]
> We got it to work by moving guava-26.0-jre.jar from webapps\oxalis\WEB-INF\lib to apache-tomcat-9.0.4\lib

Yes ! This is working fine.
Thanks a lot
