### ISSUE TITLE
"xsi"-namespace is being removed from the property "schemaLocation" during sending

### ISSUE THREAD

**Issue by Swiffern** [difi/oxalis#321]
These are the properties on the Invoice-element in the file that we send through Oxlias (Or some of them):

`<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 UBL-Invoice-2.1.xsd "...`

But from the output of Oxalis-standalone (Oxalis 4.0.0 RC3) we see that the "xsi"-namespace is missing from schemaLocation, and the document is invalid.

**Comment by klakegg** [comment]
`schemaLocation` should not be used as the location will be wrong for the receiver.

Is this a problem related to outbound or inbound?

**Comment by Swiffern** [comment]
It was changed before being sent, as far as I could see from the log-output from Oxalis-standalone.

I can leave out the attribute when generating the xml (before sending it to the accesspoint), 
but should Oxalis change the payload of the transaction?

**Comment by klakegg** [comment]
Oxalis performs no parsing of payload when payload is wrapped in the mandatory SBDH. Did you wrap the payload in SBDH?

**Comment by sandoor** [comment]
Problem is with oxalis-standalone.java

Fix this
https://github.com/difi/vefa-peppol/blob/master/peppol-sbdh/src/main/java/no/difi/vefa/peppol/sbdh/util/XMLStreamUtils.java

you are loosing the attribute prefix while copying.....

**package** 
no.difi.vefa.peppol.sbdh.util.XMLStreamUtils;
**file**
XMLStreamUtils.class
**class**
public class XMLStreamUtils {
**method**
public static void copy(XMLStreamReader reader, XMLStreamWriter writer) throws XMLStreamException {
                    
**Line 72**					
for (int i = 0; i < reader.getAttributeCount(); i++)
       writer.writeAttribute(reader.getAttributeLocalName(i), reader.getAttributeValue(i));
						
**replace with** 
   writer.writeAttribute(**_reader.getAttributePrefix(i),_** reader.getAttributeLocalName(i), reader.getAttributeValue(i));

**Comment by klakegg** [comment]
Closed in difi/vefa-peppol#23. Fix is included in Oxalis 4.0.1.
