### ISSUE TITLE
Certificate does not have a valid expiration date.

### ISSUE THREAD

**Issue by gunnarvo** [difi/oxalis#322]
Hi!
Running Java 9.0.4 and trying to install Oxalis 4.0.0
When testing with the oxalis-standalone.jar I use the following command to send a document to difis test AP:
java -jar --add-modules java.xml.bind .\oxalis-distribution-4.0.0-distro\bin\oxalis-standalone.jar -f Test_810418052.xml -r 9908:810418052 -s 9908:981641205
and I get the following error:
Certificate does not have a valid expiration date.
But my certificate indeed expires october 2019 (and there is nothing invalid about that date...)

Does anyone have any idea how i can get around this problem?

Gunnar Vøyenli

**Comment by klakegg** [comment]
Oxalis is tested with Java 8 only. Running any other Java versions is not officially supported.
