### ISSUE TITLE
Parsing of the header-attribute "micalg" not supporting quotes around its value.

### ISSUE THREAD

**Issue by Swiffern** [difi/oxalis#325]
The following header will result in an error on the receiving end:

`content-type: multipart/signed; boundary="d05494e4-f0c2-42fe-a7d0-be7df4448a1e"; protocol="application/pkcs7-signature"; micalg="sha1"`

Errormessage:
`Digest method '"sha1"' not known.`

Should parsing of the attribute "micalg" not allow quotes around its value?
Using Oxalis 4.0.0-RC3.

**Comment by klakegg** [comment]
Fixed by #326.
