### ISSUE TITLE
oxalis4 smime compability fail

### ISSUE THREAD

**Issue by bruker82384** [difi/oxalis#329]
Our accesspoint is unable to send to Oxalis 4, but works fine on other accesspoints including Oxalis 3.
The error message is Invalid message digest. / Disposition: automatic-action/MDN-sent-automatically; failed/error: integrity-check-failed.

The signed content verifies OK with openssl (and of course all other accesspoints), so there seems to be something either incorrect with Oxalis 4 verification, or perhaps compability issues with unknown parameters.
The error message doesn't tell me what exactly the problem is, so it is possible to get more information?

The http content is located here: 
https://mail.netclient.no/file_link?id=279&password=12601400609668236800x7f64d407539015240624522045790483819157980

Content-type of the invoice bodypart was changed to text/plain because openssl cli doesn't recognize xml, but the smime signature is correct.

You can verify that the signature is ok with openssl:
openssl smime -in ehf.p7m -verify -CAfile peppol.ca -purpose sslclient

**Comment by klakegg** [comment]
Please upload content for persistency rather than providing links expected to die in the future.

**Comment by LaurensN** [comment]
@bruker82384 Have you resolved this? Seeing this too, accepted by Oxalis 3 AP, but rejected by Oxalis 4 AP with invalid digest. I'll provide examples ASAP.
