### ISSUE TITLE
 Common Name (CN) attribute extraction pattern is not matching with OpenPEPPOL PKI v3 certificate

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#332]
CN regex pattern CN_PATTERN = "CN=([^,]*)," in Oxais **3.2** and PATTERN_CN = Pattern.compile("CN=([^,]*),") in Oxalis **4.0.1** is not matching with OpenPEPPOL PKI v3 certificate 

**Oxalis version 4.1:**
1) Error injecting constructor, java.lang.IllegalArgumentException: Unable to extract the CN attribute from C=YY,O=XXXXX,OU=PEPPOL TEST AP,CN=POP0000XX
  at no.difi.oxalis.as2.outbound.As2MessageSender.<init>(As2MessageSender.java:129)
  while locating no.difi.oxalis.as2.outbound.As2MessageSender

**Oxalis version 3.2:**
1) Error in custom provider, java.lang.IllegalArgumentException: Unable to extract the CN attribute from C=YY,O=XXXXX,OU=PEPPOL TEST AP,CN=POP0000XX
  at eu.peppol.outbound.transmission.TransmissionModule.ourCommonName(TransmissionModule.java:26)
  while locating eu.peppol.security.CommonName annotated with @com.google.inject.name.Named(value=OurCommonName)
    for parameter 2 at eu.peppol.outbound.transmission.Transmitter.<init>(Transmitter.java:35)
  while locating eu.peppol.outbound.transmission.Transmitter

P.S. XXXXX is used to hide organization name, YY to hide country code and XX to hide service provider ID.

**Comment by jannewaren** [comment]
Would it be possible to fix this for Oxalis 3.2 also, like, release a new patch version 3.2.1 or something?

I know at this point Access Points should be using Oxalis 4 for sending but I'm a bit afraid there might be some Access Points that will not be using Oxalis 4 or fixed this on their own next week.

On Monday 3.9.2018 Access Point Providers can start using their new PKIv3 certificates according to https://openpeppol.atlassian.net/wiki/spaces/OPMA/pages/189530542/PKI+Certificate+Migration+2018 - as soon as anyone updates their certificate to be PKIv3 in the SMP - everyone using Oxalis 3.2.0 to send to that AP will start failing.

Or is it the general opinion that everyone is already using Oxalis 4.0.2 next week and everything will be fine? :) That would be nice but I somehow doubt it.
