### ISSUE TITLE
schemaLocation prefix xis blir borte i Oxalis 4 

### ISSUE THREAD

**Issue by e213884** [difi/oxalis#333]
Beskrivelse:
"Etter å ha fingransket – og selv testet en mistanke - så mener jeg å ha funnet følgende feil – som bør rapporteres inn som en «Issue»:

Dette dreier seg om bruk av schemaLocation attributt på rot-elemementer (som enkelte kunder legger på).

Dersom vi sender fra oss korrekt (eks.) :

<Order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Order-2"
  xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
  xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
  xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Order-2 UBL-Order-2.1.xsd">

Så ser det vi mottar slik ut (utsending med Oxalis 4.0 outbound, og mottak via Oxalis 4.0 inbound):

<Order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Order-2" xmlns:cac="urn:oasis:names:spec
ification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Order-2 UBL-Order-2.1.xsd">

Her mangler nå «schemaLocation» angivelse av namespace (xsi) prefix – og dermed feiler validering fatalt I standard XSD validering (for de som evt. ikke har «filtrert» bort slikt).
Vi oppdager også et slikt avvik i vår produksjon – og vil dermed levere slike dokumenter til mottaker med anmerkning om at filen ikke var valid.

Uten å vite noe med sikkerhet – vil jeg tro at problemet dukker opp i samband med innpakking i SBDH i utgående implementasjon.

Vi har foreløpig «løst» problemet – med å fjerne hele attributtet på alle utgående meldinger.

**Comment by klakegg** [comment]
This is an international community, posting non-english issues is not appreciated.

Please explain (in english) how this issue is different from #321.

**Comment by e213884** [comment]
Looks like this is the same.
