### ISSUE TITLE
Configure two production certificates pki v3 and pki v2 in Oxalis conf

### ISSUE THREAD

**Issue by itEnercomSwiss** [difi/oxalis#339]
Hi,

in according to the specifications of the OpenPEPPOL AISBL authority, starting from the 3th September until the end of November, we have to use both the production certificate PKI v2 and PKI v3. 

Is it possible to configure Oxalis in order to use, at the same time, the two production certificates PKI v2 and PKI v3? 

Thanks in advance

Best regards
Davide Ciannamea

**Comment by PPotappel** [comment]
As far as I can see it, you only need to support the CA's of V2 and V3 for a short period.
This way you can support certificates of access point using V2- and V3-certificates.
After that you may only support the CA's of V3.
In between you should replace your current V2-certificate by a V3-version.

**Comment by kdkanishka** [comment]
@PPotappel Hi, Can please elaborate more on this? In which way we can support pki v2 and v3 ?
Could not find a configuration in the oxalis documentation.
https://github.com/difi/oxalis/blob/master/doc/configuration.adoc
https://github.com/difi/oxalis/blob/master/doc/keystore.md

Thanks,
Best Regards,
Kanishka

**Comment by PPotappel** [comment]
If you upgrade to Oxalis 4.0.3 both CA's are supported, as far as I can see.
Unfortunately we can not test yet as we are encountering a problem when we try to send something with version 4.0.3.

**Comment by kdkanishka** [comment]
Thanks @PPotappel ! Will check.

Best Regards,
Kanishka

**Comment by itEnercomSwiss** [comment]
Thank you @PPotappel

**Comment by robrechtD** [comment]
I have the same issue. 
The peppol documentation states that: "All APs MUST be able to support receiving transactions initiated using BOTH available PKI certificates (v2 and v3)." 
I assume we have to support both V2 and V3 certificates on our AP.
I have placed both certificates in one keystore, yet I can only figure out how to support one or the other with the oxalis.keystore.key.alias property in the oxalis.conf file. 
When I select the PKI v3 cert, an error is thrown when trying to transmit files to this AP concerning a mismatch between the AS2 endpoints. i.e. people are attempting to transmit files using our AS2 V2 endpoint (APP000...) and we are only receiving at our AS2 v3 endpoint (PBE000...)

Is it possible to support both certs in one endpoint?
