### ISSUE TITLE
Problem sending documents

### ISSUE THREAD

**Issue by jeroenslikker** [difi/oxalis#340]
We upgraded from 4.0.0 to 4.0.2 and since cannot send documents. We get the following error

Message failed : no.difi.vefa.peppol.common.lang.EndpointNotFoundException: Combination of 'cenbii-procid-ubl::urn:www.cenbii.eu:profile:bii04:ver2.0' and transport profile(s) not found.

We cannot figure out what is going wrong. Please help :-)

**Comment by PPotappel** [comment]
Attached is the complete logging of a session with this error.
[error.log](https://github.com/difi/oxalis/files/2332231/error.log)

**Comment by PPotappel** [comment]
Exact the same file with the same certificate does work with version 4.0.0.

**Comment by PPotappel** [comment]
If we skip the use of the SMP and use the commandline, the sending of documents is no problem.

**Comment by PPotappel** [comment]
Problem found!
The ProcessIndentifier in the XML-document was different from the one in the SML.
It looks like Oxalis 4.0.3 checks the ProcessIdentifier stricter as version 4.0.0 did.
