### ISSUE TITLE
Bug in CommonName extraction

### ISSUE THREAD

**Issue by GaitBoxman** [difi/oxalis#342]
In security/CommonName.java, the routine to get the CN from the DN is flawed, when the CN is at the end of the DN, the regexp is not matched because it expects a comma as the terminator. To fix this, I added a trailing comma to the DN in the string assignment:
        String distinguishedName = x500Principal.getName() + ",";

This is for both release4 and 3.1.1.
For some reason, it only pops up now that V3 certificates are being issued where the CN is at the end of the DN...

--Gait.

**Comment by PPotappel** [comment]
Upgrading to version 4.0.2 or 4.03 helps too ;)

**Comment by klakegg** [comment]
@GaitBoxman, please clarify how this issue is different from the solved issue #332?

**Comment by GaitBoxman** [comment]
Looks like the same, but I didn't notice it was patched there. BTW, I'm 
running release4 and 3.0.2., and changes to 4.0.2. are a lot wider than 
just adding the comma to make the matching work. When you have a new 
production release of AS4 enabled version that is stable enough, I'll be 
happy to try it, but until then I'm not going to try and follow 
extensive updates on a live system.

BTW, another provider contacted me with similar problem in 4.0.2, and 
only then I noticed you changed the code there and had a fix, so I told 
them to upgrade, which worked :-)

-- Gait.

**Comment by christian-andersson** [comment]
Just want to point out that there is no 4.0.3 release, atleast I cannot find any tag for it, and there is also nothing released with version 4.0.3 on maven repo.

If 4.0.3 is "master" branch that it is not something I would ever put in production.

**Comment by klakegg** [comment]
@christian-andersson, please clarify which changes done to master you don't like.

**Comment by christian-andersson** [comment]
@klakegg I have no problems with any changes, but is a moving target therefore it should not be used in production, if you say that 4.0.3 is the same as master, it means that if I check out master today and put it in production, you fix something tomorrow and push to master and then tell me to use 4.0.3 to fix the bug I have. well I am already using 4.0.3 but behind.

also master is not deployed to the maven repo. (unless you deploy to maven repo as snapshots, but again, you should not use snapshots for production either)

if you want us to use 4.0.3, tag a commit as 4.0.3, build it and deploy to maven repo, if you do a fix. tag it as 4.0.4, build it and deploy to maven repo.
