### ISSUE TITLE
use pkcs12 instead of jks as keystore

### ISSUE THREAD

**Issue by christian-andersson** [difi/oxalis#343]
Java keytool now recommends that pkcs12 should be used instead of jks
"The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using ..."

It would be a lot easier to handle the keys in oxalis if we did not had to have to convert between keystores all the time.

**Comment by klakegg** [comment]
Please provide the error you receive when using a PKCS12 keystore.

**Comment by christian-andersson** [comment]
So what you are saying si that it is possible? ok then why dont the documentation say anything about this? as far as I can see all the documentation points only mentions usage of jks, if jks is no longer needed, then the documentation should be updated to reflect this. it will create a lot less work for us that use oxalis if we can skip the whole java keytool and only use openssl.

Also the documentation on hot to create certificates, etc does not reflect the new reqality where you get this generated for you via openpeppol system.

**Comment by klakegg** [comment]
Thank you for your rant. May I now have some feedback on my previous request?

**Comment by christian-andersson** [comment]
Yes it worked, but this is not something we should have to do trial and error about.
