### ISSUE TITLE
Getting an exception when sending the document to PEPPOL for OIN

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#344]
We were getting the following exception when trying to send to PEPPOL yesterday 04 Sep 2018.

The Access Point URL for the OIN Identifier (9954:00000001856305765000) is 

https://gateway.simplerinvoicing.tiekinetix.net:8443/oxalis/as2

Unable to provide end point data for 9954:00000001856305765000 for urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol4a:ver2.0:extended:urn:www.simplerinvoicing.org:si:si-ubl:ver1.1.x::2.1
at eu.peppol.smp.SmpLookupManagerImpl.getEndpointTransmissionData(SmpLookupManagerImpl.java:179)

Could you anyone help us why it got failed recently.

**Comment by jeroenslikker** [comment]
which version off Oxalis? >400 is strict on <cbc:ProfileID>urn:www.cenbii.eu:profile:bii04:**ver2.0**</cbc:ProfileID>, when it does not exist in SMP you will nog get end point data. You can use -p to overule profile-id in document.

**Comment by VijayaKumar2** [comment]
Currently we are using Oxalis 4.00.

But the identifier is available in the SMP.


![image](https://user-images.githubusercontent.com/9033805/45087108-75e8de00-b122-11e8-93ce-fd6a97dbf250.png)

**Comment by klopojed** [comment]
This can be related to CN problem fixed only in version 4.0.2. If not fixed, exactly such exception is thrown when sending to AP with X500Principal ending with CN (as in this case). We're struggling with similar problem and the same error message right now. BTW, it would be nice not to swallow the previous exception replacing it with "Unable to provide endpoint data"

**Comment by VijayaKumar2** [comment]
So if we want solve this, we need to upgrade to 4.0.2 latest version ?

**Comment by andersode** [comment]
We strongly urge you to update to 4.0.2 as soon as possible earlier versions have bugs.

**Comment by VijayaKumar2** [comment]
Thanks, We will try to upgrade to the latest version. I hope this won't affect the existing integration in the network for sending and receiving document.

**Comment by VijayaKumar2** [comment]
We are seeing the latest version 4.0.3 already available, shall we move to that version now or we should go with 4.0.2 only. Any suggestion on this please.
