### ISSUE TITLE
no.difi.oxalis.api.lang.OxalisTransmissionException: Unable to verify signature

### ISSUE THREAD

**Issue by l0ddifyr** [difi/oxalis#356]
After upgrade to 4.0.2, I get an error in 
TransmissionResponse response = transmitter.transmit(transmissionRequest);

Anyone have any insights on this error?:

Log of error: 
`INFO   | jvm 1    | 2018/09/19 19:24:42 | no.difi.oxalis.api.lang.OxalisTransmissionException: Unable to verify signature.
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:310) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:233) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:149) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:135) ~[oxalis-outbound-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:100) ~[oxalis-outbound-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at com.reknes.ap.bluegrass.oxalis.OxalisOutbound.send(OxalisOutbound.java:94) ~[reknes-bluegrass-1.0.0.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at com.reknes.ap.bluegrass.Client.messageReceived(Client.java:165) [reknes-bluegrass-1.0.0.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at com.reknes.ap.bluegrass.ovary.RabbitMqConsumer.fireMessage(RabbitMqConsumer.java:75) [reknes-bluegrass-1.0.0.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at com.reknes.ap.bluegrass.ovary.RabbitMqConsumer.handleDelivery(RabbitMqConsumer.java:33) [reknes-bluegrass-1.0.0.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:140) [amqp-client-3.3.1.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:85) [amqp-client-3.3.1.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
INFO   | jvm 1    | 2018/09/19 19:24:42 | Caused by: java.lang.IllegalStateException: Unable to create SMIMESignedParser: can't extract input stream: java.io.IOException: The system cannot find the path specified
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.util.SignedMimeMessage.parseSignedMessage(SignedMimeMessage.java:186) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.util.SignedMimeMessage.<init>(SignedMimeMessage.java:82) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:308) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	... 14 more
INFO   | jvm 1    | 2018/09/19 19:24:42 | Caused by: javax.mail.MessagingException: can't extract input stream: java.io.IOException: The system cannot find the path specified
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at org.bouncycastle.mail.smime.SMIMESignedParser.getTmpFile(Unknown Source) ~[bcmail-jdk15on-1.57.jar:1.57.0]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at org.bouncycastle.mail.smime.SMIMESignedParser.<init>(Unknown Source) ~[bcmail-jdk15on-1.57.jar:1.57.0]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.util.SignedMimeMessage.parseSignedMessage(SignedMimeMessage.java:184) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.util.SignedMimeMessage.<init>(SignedMimeMessage.java:82) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:308) ~[oxalis-as2-4.0.2.jar:?]
INFO   | jvm 1    | 2018/09/19 19:24:42 | 	... 14 more`

**Comment by cook32** [comment]
Do you use PKI v3 ?

**Comment by l0ddifyr** [comment]
Yeah... Maybe I have solved it now. Just waiting on verification that the ehf has been received.
