### ISSUE TITLE
Need Fix for Disabling "chunked" Tranfer-Encoding header in Oxalis 4.0.2, sets default by http1.1

### ISSUE THREAD

**Issue by madhawaudayakantha** [difi/oxalis#357]
We have switched to new Oxalis 4.0.2 (For sending outgoing documents to endpoints) which use http1.1 instead of http1.0 and it changed to the behavior of HTTP chunked encoding set as default, bause http1.1 set this by default.
Moving for http1.1 with Tranfer-Encoding header with  "chunked" is causing problems for some of endpoints (As they are not supporting chunk encoding at their side), where they work very well with the Oxalis earlier released versions.

Could you please fix this in Oxalis code to support  for disabling this  Chunked Tranfer-Encoding mechanism in http1.1, or to support http1.0 to overcome this problem.

**Comment by samdearden** [comment]
@madhawaudayakantha Did you manage to work around this or did you endpoints start accepting chunked messages?

**Comment by thebilge** [comment]
@madhawaudayakantha could you please provide information how you fixed this or why you closed the issue otherwise it should be reopened since it is still the case and a fix required to disable "chunked" Transfer-Encoding header, maybe a config property to force http1.0.

**Comment by madhawaudayakantha** [comment]
@samdearden @thebilge :+1: 
Hi all, the receiving endpoints start accepting chunked transfer encoding. That's why I closed the case.
