### ISSUE TITLE
Signers certificate is neither verfified nor validated in oxalis 4.0.2 - Serious Security Issue

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#358]
In Oxalis 4.0.2, verification code is commented out:

            // Verify that the signature is correct and that signersIterator was generated when the certificate was current
            /*
            try {
                if (!signer.verify(new JcaSimpleSignerInfoVerifierBuilder().setProvider(BouncyCastleProvider.PROVIDER_NAME).build(signersX509Certificate))) {
                    throw new IllegalStateException("Verification of signer failed");
                }
            } catch (CMSException | OperatorCreationException e) {
                throw new IllegalStateException("Unable to verify the signer. " + e.getMessage(), e);
            }
            */

In Oxalis 3.2,  verification was there after issue: https://github.com/difi/oxalis/issues/220 was reported, like below:
            // Verify that the signature is correct and that signersIterator was generated when the certificate was current
            try {
                if (!signer.verify(new JcaSimpleSignerInfoVerifierBuilder().setProvider(PROVIDER_NAME).build(signersX509Certificate))) {
                    throw new IllegalStateException("Verification of signer failed");
                }
            } catch (CMSException e) {
                throw new IllegalStateException("Unable to verify the signer. " + e.getMessage(), e);
            } catch (OperatorCreationException e) {
                throw new IllegalStateException("Unable to verify the signer. " + e.getMessage(), e);
            }

**Even in Oxalis 4.0.2, there is no validation of certificate. It is serious issue.** 
  
In 3.0.2, there was validation logic:
    private void validateCertificate(X509Certificate certificate) {

        try {

            List<X509Certificate> certificateList = new ArrayList<X509Certificate>();
            certificateList.add(certificate);

            CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
            CertPath certPath = certificateFactory.generateCertPath(certificateList);

            // Create the parameters for the validator
            KeystoreManager keystoreManager = KeystoreManager.getInstance();
            PKIXParameters params = new PKIXParameters(keystoreManager.getPeppolTruststore());

            // Disable revocation checking as we trust our own truststore (and do not have a CRL and don't want OCSP)
            params.setRevocationEnabled(false);

            // Validate the certificate path
            CertPathValidator pathValidator = CertPathValidator.getInstance("PKIX",PROVIDER_NAME);
            CertPathValidatorResult validatorResult = pathValidator.validate(certPath, params);

            // Get the CA used to validate this path
            PKIXCertPathValidatorResult result = (PKIXCertPathValidatorResult) validatorResult;
            TrustAnchor ta = result.getTrustAnchor();
            X509Certificate trustCert = ta.getTrustedCert();

            log.debug("Trusted cert was : {}", trustCert.getSubjectDN().toString());

        } catch (Exception e) {
            throw new IllegalStateException("Unable to trust the signer : " + e.getMessage(), e);
        }

    }

**Comment by klakegg** [comment]
Please explain why it is a serious issue that Oxalis 4 does not revalidate receiving AP certificate after transmission.

**Comment by klakegg** [comment]
Please provide feedback on this Serious Security Issue.
@aaron-kumar

**Comment by klakegg** [comment]
It has been six weeks and no further feedback from @aaron-kumar on this Serious Security Issue.
