### ISSUE TITLE
Question about development environment

### ISSUE THREAD

**Issue by EU-Supply-Renier** [difi/oxalis#359]
Is it possible to Set up Oxalis 4.0 AS4 plugin on a development environment with out a PEPPOL test certificate?

**Comment by klakegg** [comment]
What is the error you get?

**Comment by EU-Supply-Renier** [comment]
We are not getting any errors. 
We just want to know if it's possible to start Oxalis API without a PEPPOL certificate on our development environment. In other words is the PEPPOL certificate always required regardless of environment (Dev, Test, Pre-Prod, Prod).

**Comment by klakegg** [comment]
Oxalis requires use of PEPPOL certificate.

**Comment by EU-Supply-Renier** [comment]
You are right one of our developers have seen that in the code.
However my point is that on a developer/tester machine it should not be required. Then most of the test scenarios you run are internally, meaning you send a document to your self in order to assert that the files are received and processed correctly through oxalis.
We do understand and see the need of a certificate in a Production and Pre-Production  environment so only authorized people/systems could access the Network but on a developer machine it should be more open.

**Comment by cook32** [comment]
You are sending on PEPPOL network so you must be trusted, so, certificate is mandatory.
