### ISSUE TITLE
Implementation of Oxalis

### ISSUE THREAD

**Issue by bgandhi1709** [difi/oxalis#366]
I have compiled a list of questions for oxalis.

1)	How do we send attachments as well as xml file using oxalis-standalone for outbound
        Currently I see in the source code that only xml payload file is getting transmitted and not 
        attachments.

2)	How does oxalis store the transmission log information i.e. its own log of actions it has performed.

3)	Is it possible to directly put inbound message from oxalis into a queue (e.g. RabbitMQ)

4)	AS4 Protocol is recommended for new implementations however I see on AS2 Implementation in source code , can you please tell us when AS4 implementation will be available.

We are integrating Oxalis for Four Corner model and need above questions to be answered so that we can move ahead.

Thank you

**Comment by artjomsk** [comment]
I'm only user of Oxalis, so my answers may not be 100% precise ;)

1. Attachments can be in Base64 or as link. For more info look here https://vefa.difi.no/ehf/guide/invoice-and-creditnote/2.0/en/#_attachments

2. In oxalis.log file. You can configure logging as you want in logback configuration file of corresponding module (ex. logback-oxalis-inbound.xml)

3. Yes, I suppose you should implement no.difi.oxalis.api.persist.PersisterHandler and do what you want.

**Comment by artjomsk** [comment]
4. Oxals with AS4 Protocol support have separate repository - https://github.com/difi/Oxalis-AS4/releases
I also would like to know when it will be available. But you can try the RC1
