### ISSUE TITLE
Oxalis implementation of reading participant id in AbstractDocumentParser does not follow BIS 4a

### ISSUE THREAD

**Issue by bahaabeih** [difi/oxalis#376]
The implementation of AbstractDocumentParser [here](https://github.com/difi/oxalis/blob/caa40f96f8cb697c0177a2994d8ab76a11268738/oxalis-extension/oxalis-document-sniffer/src/main/java/no/difi/oxalis/sniffer/document/parsers/AbstractDocumentParser.java#L70) doesn't allow the following excerpt in documents:
```
   ...
   <cac:Party>
     <cbc:EndpointID schemeID="DE:VAT">DE123456789</cbc:EndpointID>
     <cac:PartyIdentification>
       <cbc:ID schemeID="DE:VAT">DE123456789</cbc:ID>
     </cac:PartyIdentification>
     ...
   </cac:Party>
   ...
```
It expects it to be as follows (check the agency id numeric code prefix):
```
   ...
   <cac:Party>
     <cbc:EndpointID schemeID="DE:VAT">9930:DE123456789</cbc:EndpointID>
     <cac:PartyIdentification>
       <cbc:ID schemeID="DE:VAT">DE123456789</cbc:ID>
     </cac:PartyIdentification>
     ...
   </cac:Party>
   ...
```
This contradicts [BIS 4a](https://github.com/OpenPEPPOL/documentation/blob/master/PostAward/InvoiceOnly4A/20170315-PEPPOL_BIS_4A-401.pdf), which lists many examples where schemes like GLN, EU:VAT and DK:CVR are used as `schemeId` attributes without numeric code prefix in the enclosed element. For example check page 30 or page 31

**Comment by klakegg** [comment]
Please see the [README](https://github.com/difi/oxalis/blob/master/oxalis-extension/oxalis-document-sniffer/README.md).
