### ISSUE TITLE
Oxalis version 4.0.3 is not released in Maven.

### ISSUE THREAD

**Issue by monze** [difi/oxalis#383]
Hey

Latest released version of Oxalis in [Maven](https://mvnrepository.com/artifact/no.difi.oxalis) is still version 4.0.2 - which does not support version 2 of PEPPOL certificates. In trunk this has been resolved (back in August), but no release of that work has yet been done.

When is version 4.0.3 planed to be released?

This has been addresses in other issue - which has been closed without any explanation.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
Version 4.0.2 is the latest release of Oxalis, thus are there no newer version available on Maven Central. 4.0.2 contains all substantial code changes done through August 2018.

Version 4.0.0 is the first version of Oxalis supporting both PEPPOL PKIs, and it is not clear to me which commit done this fall made any changes in this regard.

Version 4.0.3 will be released when it is done. It is not clear to me where release date of version 4.0.3 has been requested in other issues.

**Comment by monze** [comment]
Since the release of v 4.0.2, several issue has been fix'ed.

If we look at this issue: Default persister is not stable #375
It was fix'ed very fast, but no release so we can't test the fix.

The consequence of not releasing is, that everybody are building they own SNAPSHOT to get the fix in the software. This result in that MAVEN is not used, and nobody know which version that is used anywhere. Even the Norwegian test portal is using a [4.0.3-SNAPSHOT](https://test-aksesspunkt.difi.no/status).

I'm just requesting a faster release cycles...

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
How is #375 related to support for version 2 of PEPPOL certificates?
