### ISSUE TITLE
Getting EndpointNotFoundException when sending ApplicationResponse

### ISSUE THREAD

**Issue by PeterOlausson65** [difi/oxalis#392]
When I try to send an ApplicationResponse message I get the error
`no.difi.vefa.peppol.common.lang.EndpointNotFoundException: Combination of 'cenbii-procid-ubl::urn:www.cenbii.eu:profile:bii36:ver2.0' and transport profile(s) not found.`

What I can see, the processIdentifier shown would come from the request message I'm trying to send.
In the SMP profile, the processIdentifier is 'urn:www.cenbii.eu:profile:bii36:ver2.0'
In my ApplicationResponse, the processIdentifier is the same as in the SMP.
```
<BusinessScope>
	<Scope>
		<Type>DOCUMENTID</Type>
		<InstanceIdentifier>urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2::ApplicationResponse##urn:www.cenbii.eu:transaction:biitrns071:ver2.0:extended:urn:www.peppol.eu:bis:peppol36a:ver1.0::2.1</InstanceIdentifier>
	</Scope>
	<Scope>
		<Type>PROCESSID</Type>
		<InstanceIdentifier>urn:www.cenbii.eu:profile:bii36:ver2.0</InstanceIdentifier>
	</Scope>
</BusinessScope>
```

```
<cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns071:ver2.0:extended:urn:www.peppol.eu:bis:peppol36a:ver1.0</cbc:CustomizationID>

<cbc:ProfileID>urn:www.cenbii.eu:profile:bii36:ver2.0</cbc:ProfileID>
```

So where does the "enbii-procid-ubl::" prefix come from when it tries to find the endpoint?
One thing I noted in the SMP is that the scheme for processIdentifier in ApplicationResponse is different from the scheme for Invoice.
ApplicationResponse:
`<ProcessIdentifier scheme="busdox-docid-qns">urn:www.cenbii.eu:profile:bii36:ver2.0</ProcessIdentifier>`
Invoice:
`<ProcessIdentifier scheme="cenbii-procid-ubl">urn:www.cenbii.eu:profile:bii05:ver2.0</ProcessIdentifier>`

Could this be the reason why it fails to send the ApplicationResponse? This is the only place where I have seen the "cenbii-procid-ubl".

**Comment by LaurensN** [comment]
Same issue:

From smp:
```
"ProcessList"=>
          {"Process"=>
            {"ProcessIdentifier"=>{"__content__"=>"urn:www.cenbii.eu:profile:bii04:ver2.0", "scheme"=>"cenbii-procid-ubl"},
             "ServiceEndpointList"=>
              {"Endpoint"=>
```
Error:

`Combination of 'cenbii-procid-ubl::urn:www.cenbii.eu:profile:bii04:ver2.0' and transport profile(s) not found.`

**Comment by LaurensN** [comment]
@klakegg Does this require any action for sending or receiving APs? Thanks.

**Comment by PeterOlausson65** [comment]
In the class no.difi.vefa.peppol.common.model.AbstractServiceMetadata
What I can see, processIdentifier comes from the SBDH document while transportProfiles comes from the SMP. What I haven't figured out yet is why does processIdentifier contain the prefix "cenbii-procid-ubl::" when it is nowhere in the SBDH or ApplicationResponse message?

```
    public T getEndpoint(ProcessIdentifier processIdentifier, TransportProfile... transportProfiles)
            throws EndpointNotFoundException {
        for (ProcessMetadata<T> processMetadata : processes)
            if (processMetadata.getProcessIdentifier().contains(processIdentifier))
                return processMetadata.getEndpoint(transportProfiles);

        throw new EndpointNotFoundException(
                String.format("Combination of '%s' and transport profile(s) not found.", processIdentifier));
    }

```

**Comment by PeterOlausson65** [comment]
I think the problem is in no.difi.oxalis.sniffer.PeppolStandardBusinessHeader, method toVefa() which is called from  no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder

The Vefa process is assigned directly from the ProfileTypeIdentifier().toString() rather than ProfileTypeIdentifier.getIdentifier()

ProfileTypeIdentifier.getIdentifier() = urn:www.cenbii.eu:profile:bii36:ver2.0
ProfileTypeIdentifier.toString() = cenbii-procid-ubl::urn:www.cenbii.eu:profile:bii36:ver2.0

**Comment by PeterOlausson65** [comment]
@klakegg egg is this problem in Oxalis software, see above comment?

**Comment by klakegg** [comment]
Closing this as people are busier looking for bugs in Oxalis than reading PEPPOL documentation and verifying SMP responses.

**Comment by PeterOlausson65** [comment]
Following the specification https://joinup.ec.europa.eu/svn/peppol/PostAward/MessageLevelResponse36A/Upcoming%20Release/PEPPOL_BIS_36A-200_2017-03-30.pdf
I try to send an application response with sbdh header using oxalis-standalone-4.0.3.jar:
```
<StandardBusinessDocumentHeader>
    <HeaderVersion>1.0</HeaderVersion>
    <Sender>
        <Identifier Authority="iso6523-actorid-upis">0007:TIETOTEST</Identifier>
    </Sender>
    <Receiver>
        <Identifier Authority="iso6523-actorid-upis">0007:TIETOTEST</Identifier>
    </Receiver>
    <DocumentIdentification>
        <Standard>urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2</Standard>
        <TypeVersion>2.1</TypeVersion>
        <InstanceIdentifier>36c00eb3-9823-5a9a-54af-b1a53bd61ba7</InstanceIdentifier>
        <Type>ApplicationResponse</Type>
        <CreationDateAndTime>2018-11-27T09:27:29.77</CreationDateAndTime>
    </DocumentIdentification>
    <BusinessScope>
        <Scope>
            <Type>DOCUMENTID</Type>
            <InstanceIdentifier>urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2::ApplicationResponse##urn:www.cenbii.eu:transaction:biitrns071:ver2.0:extended:urn:www.peppol.eu:bis:peppol36a:ver1.0::2.1</InstanceIdentifier>
        </Scope>
        <Scope>
            <Type>PROCESSID</Type>
            <InstanceIdentifier>urn:www.cenbii.eu:profile:bii36:ver2.0</InstanceIdentifier>
        </Scope>
    </BusinessScope>
</StandardBusinessDocumentHeader>
```
I then get the error

> Message failed : Combination of 'cenbii-procid-ubl::urn:www.cenbii.eu:profile:bii36:ver2.0' and transport profile(s) not found.

The recipient is registered in Galaxy GW SMP, but we also had the same issue when the recipient is in ELMA.

**Comment by klakegg** [comment]
1. Oxalis behaves correctly according to PEPPOL specifications, thus was this issue tagget with "Not Oxalis".
2. It is not clear to me why it takes 23 days to provide necessary information about the lookup done.
3. Compliance issues in PEPPOL are not handled by neither creating an issue in the Oxalis issue tracker nor by tagging me in issues clearly not indicating bugs in Oxalis.

Please report any compliance issues in the [OpenPEPPOL Service Desk](https://openpeppol.atlassian.net/servicedesk/customer/portal/1) and delete the participant 0007:TIETOTEST from PEPPOL production as this is clearly not a valid Swedish organization number.

**Comment by PeterOlausson65** [comment]
Thanks, finally found the document https://peppol.eu/openpeppol-release-of-sbdh1-1/ from september 2018 where there is a new Identifier element in the business scope for use with non-standard process scheme.
```
        <Scope>
            <Type>PROCESSID</Type>
            <InstanceIdentifier>urn:www.cenbii.eu:profile:bii36:ver2.0</InstanceIdentifier>
             <Identifier>busdox-docid-qns</Identifier>
        </Scope>
```

**Comment by PeterOlausson65** [comment]
Standard as you probably know is  cenbii-procid-ubl. But as seen, the ApplicationResponse does not use standard scheme. This was no problem when using SBDH version 1.0 (with old Oxalis) as the scheme was not considered when finding the endpoint. With the 4.0 versions of Oxalis I understand though we must use SBDH version 1.1.
For us this only affects sending ApplicationResponse which is not that common. Even if we encounter schematron errors received files, most of the times the sender does not have an ApplicationResponse profile or is not even registered in an SMP.

**Comment by klakegg** [comment]
@PeterOlausson65 Where may I find information about ApplicationResponse messages using a different process scheme?

**Comment by PeterOlausson65** [comment]
I found it here:
https://www.galaxygw.com/peppol-documents/

**Comment by klakegg** [comment]
That was not our intention, it is now fixed. What is status on the normative source for this?
