### ISSUE TITLE
Oxalis and Wildcard certificate

### ISSUE THREAD

**Issue by gunnarvo** [difi/oxalis#408]
Hi!
Using Oxalis 4.0.2, Java 1.8.0_181
When sending documents to Access Points which have wildcard SSL certificate the sending fails.
It seems to me that Oxalis does not allow wildcard certificates? If so, I think it should.

Regards,
Gunnar Vøyenli
Xledger Labs AS

**Comment by jannewaren** [comment]
We have been using a wildcard certificate in production for our PEPPOL AP for many years and it has worked properly with Oxalis 3.X and Oxalis 4.X.

Maybe you should paste some logs here, for example how exactly does it fail.

**Comment by klakegg** [comment]
@gunnarvo Please send a transmission to 9908:810418052 and post the exception you receive here.

**Comment by gunnarvo** [comment]
Thanks for the reply.
Tried to send a test invoice to Difi, 9908:810418052 (which has a wildcard certificate) and it was delivered successfully.

Then my problem might be related to something else. Have to dig more into it.

Gunnar
