### ISSUE TITLE
Sending Non peppol documents using Oxalis

### ISSUE THREAD

**Issue by abhiroopgupta** [difi/oxalis#412]
We are using Oxalis to perform CEF eDeliver core connectivity test.

The Test requires us to send the following XML file to eDelivery Test Access point.

**<?xml version="1.0" encoding="UTF-8"?>
<Request>eDelivery AS4 Connectivity test.Sending Message</Request>**

I have tried to send the document using the command :
**java -classpath "api/*;as4/*;bin/*" eu.sendregning.oxalis.Main -f resources/test4.xml -u http://40.115.23.114:8080/domibus/services/msh?domain=static -s ceftestparty58gw -r cefsupportgw -protocol  peppol-transport-as4-v2_0 -cert cert/ceftestparty58gw.crt**

Since this is a non peppol business document, I get an error because probably validating the document as a peppol business document fails.

java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1

How can I send the above document using Oxalis?
Any configuration options that are required or Additional Oxalis Standalone parameter needed to send this XML?

**Comment by evenos** [comment]
A quick reply:
You have written the parameter ```--protocol``` wrong. Note the two dashes.

Note that in this setup OxalisStandalone will try to determine the profile and document type from the SBDH payload. You can try to sett these parameters manually ( ```-p``` and ```-d``` )

I will look more closely on this issue.

**Comment by evenos** [comment]
First, one additional ting related to your setup. Your classpath references needs to include the entire directory (the folder name needs to be followed by a *) of jars.

I have added my working example for sending PEPPOL documents below as a working example. Here I have to folders of jars, one for Oxalis (downloaded and extracted from [Maven Central](https://mvnrepository.com/artifact/no.difi.oxalis/oxalis-distribution/4.0.3)) and one for AS4 (downloaded and extracted from [GitHub releases](https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0-RC4)). The file I am sending is an example file from [Oxalis unit tests](https://github.com/difi/oxalis/blob/master/oxalis-dist/oxalis-standalone/src/test/resources/BII04_T10_PEPPOL-v2.0_invoice.xml)

```shell
java -classpath "oxalis-distribution-4.0.3-distro/api/*;oxalis-as4-4.1.0-SNAPSHOT-dist/*;oxalis-distribution-4.0.3-distro/bin/*" eu.sendregning.oxalis.Main -f examples/BII04_T10_PEPPOL-v2.0_invoice.xml -u http://localhost:8282/oxalis/as4 --cert oxalis_c3.cer --protocol peppol-transport-as4-v2_0
```

So, to the more complicated issue of sending files not related to PEPPOL. Short answer, Oxalis is not ment to support non PEPPOL files.

The long answer. You can technically send arbitrary files trough the [Transmitter](https://github.com/difi/oxalis/blob/4264886a1a99b33135fd11215091b29676926e66/oxalis-api/src/main/java/no/difi/oxalis/api/outbound/Transmitter.java) interface using Oxalis-outbound directly. Oxalis-standalone will technically let you send arbitrary files, but will validate that the Document Type Identifier follows [PEPPOLS specifications](https://github.com/difi/oxalis/blob/master/oxalis-legacy/oxalis-document-sniffer/src/main/java/no/difi/oxalis/sniffer/identifier/PeppolDocumentTypeId.java#L58)

```regexp
(.*)::(.*)##(.*)::(.*)
```

On the receiving end Oxalis-AS4 will parse and validate the transmitted file under the assumption that they are SBD files containing an SBDH, so it will not be able to receive non PEPPOL files. Oxalis 4.0.2 introduced support for [pluggable header parsing](https://github.com/difi/oxalis/commit/d306d28ad8d0a0d27f7a1d83ebb9cb9be587367d) but this in not yet implemented in Oxalis-AS4.

As a last friendly tip to connectivity testing. Ask the testers if you can send you an SBD file. But the  Document Type Identifier will stil be a problem.

Hope this helps to clarify.
