### ISSUE TITLE
Unable to load class loader for '/opt/oxalis-conf/oxalis-plugin'

### ISSUE THREAD

**Issue by Olafghx** [difi/oxalis#413]
Hello,

Our serviceprovider installed Oxalis for us and testing the outbound message went without problems. 
Testing the inbound message (command: java -jar /opt/oxalis/target/oxalis-standalone.jar -f /opt/oxalis/oxalis-dist/oxalis-standalone/src/test/resources/BII04_T10_PEPPOL-v2.0_invoice.xml -u http://localhost:8180/oxalis/as2 -cert /opt/oxalis-conf/ghx.cer) gave an error:
[oxalis-root-test-inbound-fail.txt](https://github.com/difi/oxalis/files/3079778/oxalis-root-test-inbound-fail.txt)

What should we do to fix the issue?

**Comment by simo385** [comment]
Hello,

I had the same problem. I fixed it removing the following lines in **oxalis.conf**:

# The relative name of the directory holding plugin
 oxalis.path.plugin = oxalis-plugin
 # Signals to Oxalis that we should look for plugin
 oxalis.persister.receipt = plugin

In this way, I'm able to receive the files.

Simone
