### ISSUE TITLE
Deprecation of SHA1 in AS2 as of Revision 2.0

### ISSUE THREAD

**Issue by cb-fred** [difi/oxalis#414]
Hi,

I see in the OpenPEPPOL AS2 spec update document that the support for SHA1 has been removed https://github.com/OpenPEPPOL/documentation/blob/master/TransportInfrastructure/PEPPOL-EDN-AS2-Profile-2.0-2019-03-14.pdf (see Revison 2.0)

Is this something that has been implemented in Oxalis ? Should we upgrade to the latest version for compliance ? I do not see anything in the release note regarding that.

Thanks,

Frederic van der Essen
CodaBox SA

**Comment by w4oeijueroiwjer** [comment]
Frederic,
Per 09-09-2018 we have verified that Oxalis4 do not support receiving SHA2-signed AS2-data and will fail with integrity-check-failed.
I am guessing the status is the same today.
Oxalis3 do however support receiving sha2-signed messages, but I am guessing no-one is running that anymore.

Jay
