### ISSUE TITLE
Oxalis 4.0.4 - info about statistics

### ISSUE THREAD

**Issue by Giovanna72** [difi/oxalis#418]
Hi,
I have installed Oxalis AP 4.0.4 and successfully sent and received a document.
Also I've configured the log using logback configuration file and the database H2.

I don't understand from documentation and from issues already present, if there is a way to activate the statistics and, if so, how.

May be DIFI does require no more the statistics so they are removed from the last releases of Oxalis? Or simply we need to ad a "plugin" to the current release to obtain them?

Thanks in advance for any suggestions!

**Comment by ign404** [comment]
@Giovanna72 how did you implement oxalis. i still dont know how to deploy oxalis

**Comment by Giovanna72** [comment]
I've followed the guide at this link: http://mmnclk.com/peppol-access-point-oxalis
I've used the Oxalis WAR presente in the oxalis-4.0.4 realease in this github and I've successfully installed either on windows server and on a linux server.
Pay attention to the certificates creation: they must be in the correct format. 
Hope this helps!
