### ISSUE TITLE
Oxalis 4.1.0 cannot send messages to Oxalis 4.0.2

### ISSUE THREAD

**Issue by cdruschk** [difi/oxalis#424]
We tried with an upgrade to Oxalis 4.1.0 today and outbound messages to many other AP's running Oxalis 4.0.2 started failing.
It looks like Oxalis 4.1.0 cannot send to Oxalis 4.0.2  because 4.0.2 rejects them
there was an issue on Oxalis 4.0.2 with the same error message ("Invalid message digest"): https://github.com/difi/oxalis/issues/380

Now the problem seems to be caused by:
https://github.com/difi/oxalis/commit/d22399406a5fb1575c69b1d64b2825c4ec287276

**Comment by klakegg** [comment]
Oxalis 4.0.3 fixed an issue related to calculation of message digest. Both Oxalis 4.0.3 and 4.0.4 contains the fix, and access points providers should update their Oxalis installations rather than running releases not containing more than a year worth of fixes and dependency updates (security!).
