### ISSUE TITLE
Oxalis Installation

### ISSUE THREAD

**Issue by ign404** [difi/oxalis#425]
Will oxalis gonna work with countries that dont have peppol authorities? both testing and implementation?

**Comment by cook32** [comment]
You should maybe learn more about PEPPOL with reading some documentation.
When no country authority is available you will sign directly with OpenPEPPOL.

**Comment by JonasZal** [comment]
Yes, it will. My Oxalis works in Lithuania and I have agreement with OpenPEPPOL.

**Comment by ign404** [comment]
What version of oxalis are you using @JonasZal ?

**Comment by JonasZal** [comment]
@ign404 
oxalis-api-4.0.3.jar
oxalis-as2-4.0.3.jar
oxalis-as4-4.1.0-SNAPSHOT.jar
oxalis-commons-4.0.3.jar
oxalis-inbound-4.0.3.jar

**Comment by ign404** [comment]
@JonasZal are you already using oxalis in webapp?

**Comment by JonasZal** [comment]
@ign404  what do you mean by webapp? Our Oxalis is running with Peppol PROD certificates and is used for AS2 traffic.

**Comment by ign404** [comment]
are you just run it in command line or in a java project like maven? @JonasZal

**Comment by ign404** [comment]
[no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 502 from https://test-aksesspunkt.difi.no/as2

im having this issue in running example. please help me fix

**Comment by ign404** [comment]
@JonasZal What version of tomcat maven and java are you using?
