### ISSUE TITLE
'Inconsistency' in logging being used (lombok annotated vs explicit slf4j)

### ISSUE THREAD

**Issue by open-gdsn** [difi/oxalis#435]
I noticed an inconsistency in the logging being used throughout oxalis. In many places things like

    private static final Logger LOGGER = LoggerFactory.getLogger(FileSystemModule.class);

are being used and in some (also many?) 

    @Slf4j (imported from lombok.extern.slf4j.Slf4j;)

Lombok only seems to be used for this. Is there a specific reason to start using lombok and then only use it for this?

**Comment by klakegg** [comment]
Lombok is currently used for logging everywhere the code is updated after adding Lombok, and is made available to all implementers using `oxalis-extension` as parent in Maven when building plugins, e.g. [Oxalis-AS4](https://github.com/difi/Oxalis-AS4).

Could you please clarify how this is bad for Oxalis and its users?

**Comment by open-gdsn** [comment]
I'm not against lombok per-say, but using it **just for logging** is like mentioned in the original post, not a real gain. You replace one line with another, but at the same time require a complete additional framework and additional plugins in IDE's and lombok needing to keep up with the increased release speed of JDK's. So the net gain in just using it for logging is imo not there (even negative). And in the current master there is still a 50-50 mix of annotations vs static. So the oaxalis code is not actually updated yet ;-).

Cheers
