### ISSUE TITLE
maven install produces error

### ISSUE THREAD

**Issue by JsonGuy** [difi/oxalis#438]
![image](https://user-images.githubusercontent.com/20183140/68846198-5c9fd200-06d5-11ea-98ca-1807fea8b998.png)

Looking at the code
![image](https://user-images.githubusercontent.com/20183140/68846243-704b3880-06d5-11ea-9656-3cddefac0dfb.png)

What Module it should be?

**Comment by JsonGuy** [comment]
Found it, thanks for the comments on top of class :)

**Comment by open-gdsn** [comment]
Next time, please don't post code as images but as text. Better for searchengines
