### ISSUE TITLE
Combination of 'cenbii-procid-ubl::urn:fdc:peppol.eu:2017:poacc:billing:01:1.0' and transport profile(s) not found.

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#454]
We are facing "Message failed : no.difi.vefa.peppol.common.lang.EndpointNotFoundException: Combination of 'cenbii-procid-ubl::urn:fdc:peppol.eu:2017:poacc:billing:01:1.0' and transport profile(s) not found. " with both Oxalis 4.1.0 and Oxalis 4.0.2 

It is especially happening when Participant Identifier behind remote AP is registered with Older document profile like "Peppol  BIS Billing Profile V2, "Peppol Ordering Profile V1" etc  and Transport profile is "AS4".   Though it is working fine when Transport profile is current "AS2 v1"

**Comment by aaron-kumar** [comment]
Since lots of AP are facing this issues. I am investigating this issue and will send pull request when I found solution with multiple versions. I hope you will not close this issue in hurry till then. Allow this as discussion forum if that benefits to most APs , instead of closing the issue

**Comment by klakegg** [comment]
Wrong registrations in SMP is not a bug i Oxalis.
