### ISSUE TITLE
Unable to fetch

### ISSUE THREAD

**Issue by senikk** [difi/oxalis#461]
In addition to lots of errors like "Identifier 'iso6523-actorid-upis::0192:995160099' is not registered in SML." every day we sometimes get also a few of these types of errors:

Unable to fetch 'http://smp.difi.no/iso6523-actorid-upis%3A%3A0192%3A922155399/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspecification%3Aubl%3Aschema%3Axsd%3AInvoice-2%3A%3AInvoice%23%23urn%3Acen.eu%3Aen16931%3A2017%23compliant%23urn%3Afdc%3Apeppol.eu%3A2017%3Apoacc%3Abilling%3A3.0%3A%3A2.1'

Oxalis AS4 4.1.6 with Oxalis 4.1.1

**Comment by klakegg** [comment]
Issues related to ELMA need to be reported to elma@digdir.no.

**Comment by FrodeBjerkholt** [comment]
The http://smp.difi.no/{participantId}/services/{documentTypeId} can return 404 when it is unable to parse the endpoint certificate.
