### ISSUE TITLE
Where to find which AP sent a document

### ISSUE THREAD

**Issue by amaters-easy** [difi/oxalis#467]
Is there any way to see which AP sent a document? It seems the receipt.dat file does not provide it and differs from different sending AP's

**Comment by artjomsk** [comment]
What you mean by which AP? Is certificate's CN like `PNO000xxx` is OK?

no.difi.oxalis.api.inbound.InboundMetadata contains certificate of sender AP.
```
no.difi.oxalis.commons.security.CertificateUtils.extractCommonName(inboundMetadata.getCertificate())
```

**Comment by klakegg** [comment]
The correct answer is provided. No need to keep this issue open.

**Comment by amaters-easy** [comment]
> The correct answer is provided. No need to keep this issue open.

For you the answer might seem as sufficient. For me it's harder to understand.
I am looking at a xml file wondering how to discover where the no.difi.oxalis.commons.security.CertificateUtils.extract part is.
I assume I have to dig into the oxalis code to figure it out. My question however was if the sending Peppol Access Point Identifier is in the XML file and if so, how to obtain it.
