### ISSUE TITLE
Question on name of file

### ISSUE THREAD

**Issue by RvanMaarenApro** [difi/oxalis#470]
Just a question, file is received now for example with filename: 85c0933c-9691-4b9b-b71c-9a96de48ade1_econnect.eu.doc.xml.  Is it possible to include for example an invoice number to this name ?

Just a thought.

Regards,

Richard

**Comment by jannewaren** [comment]
_Disclaimer: I'm not an admin in this repository or anything like that so my answer does not represent the official opinion of anyone but me._

I think this would be a little bit too much, going outside of the scope of Oxalis.

First: Oxalis is not made for just transferring invoices, it could also be Orders or Catalogues or literally anything inside a `<BinaryContent>` that does not have such an number like invoice number.

Second: It would require looking inside the payload. That means understanding the structure of each invoice format so some extent. Could be done of course but if you really want it you could build your own plugin that `implements PersisterHandler` and do that.

It's quite easy to build such a plugin with just a little Java knowledge and we have done it ourselves (for a different purpose) - at some point we could probably share our experiences a bit. Still, building a plugin that finds out the invoice number is maybe not the thing I would do for reasons above.

Best regards,

Janne Warén
Visma.net AutoInvoice
