### ISSUE TITLE
Test send message Message failed : Certificate does not have a valid expiration date.

### ISSUE THREAD

**Issue by vincentpwnz00r** [difi/oxalis#471]
Hi,

i tried to send the sample invoice to Difi's test access point but encountered an error 

Message failed : Certificate does not have a valid expiration date.

I checked the certificate given by peppol and it is still valid till Wed Mar 23 16:59:59 PDT 2022. What causes this error?

**Comment by Tickstar** [comment]
Difi's Test AP was taken offline in January as mentioned on https://vefa.difi.no/peppol/announcement/2020-01-13-removal-of-access-points-for-testing

**Comment by vincentpwnz00r** [comment]
Hi Trickstar, thank you for the reply

I tried **Sending a sample invoice to your own local access point** and faced this issue 

Exception in thread "main" no.difi.certvalidator.api.CertificateValidationException: signed fields invalid

is there anything wrong with the certificate that peppol issued to me or my implementation?

**Comment by vincentpwnz00r** [comment]
I think it might be a wrong cert type i was using .cer fiel returns a different issue
