### ISSUE TITLE
Oxalis not working after renewing certificate

### ISSUE THREAD

**Issue by KnyGoo** [difi/oxalis#473]
Hi,

We should renew our peppol certificate soon because it will expire, but after including the new certificate testbed fails with following message. (We have an issue when receiving documents.)

**For AS2**
Transaction (with instance identifier *****) to testing AP failed to be delivered. Error; Unable to verify content of MDN using certificate provided by SMP..

Stacktrace:
No stacktrace but something wrong with MDN.

**For AS4**
Transaction (with instance identifier *****) to testing AP failed to be delivered. Error; Failed to send message.

Stacktrace:
org.apache.wss4j.dom.processor.EncryptedKeyProcessor.getPrivateKey(EncryptedKeyProcessor.java:266)org.apache.wss4j.common.crypto.Merlin.getPrivateKey(Merlin.java:624)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: Cannot find key for certificate

Seems like something is wrong with the new certificate? Certificate is working to connect to testbed. Old certificate still works. Anyone an idea?

With kind regards,

Kenny

**Comment by dudewaaagh** [comment]
Interested, having exactly the same issues.

**Comment by KnyGoo** [comment]
Issue resolved: https://github.com/difi/Oxalis-AS4/issues/123
