### ISSUE TITLE
Issue after updating certificate.

### ISSUE THREAD

**Issue by toreholazets** [difi/oxalis#482]
Hello,

We have recently encountered an issue after updating the peppol certificate. Receiving AS2 work just fine, but AS4 stops. 

I've attached the error as it appears in our logs. It seems to me to be a configuration issue, especially since it works perfectly when we swap the certificates back.  If someone could point us in the right direction, that would be helpful. 

[error.txt](https://github.com/difi/oxalis/files/5014739/error.txt)

**Comment by Olive3862** [comment]
Hi,
I can help you.
Please contact me on olive.imz@outlook.com.
