### ISSUE TITLE
Chain of trust for certificate in SMP response should be checked

### ISSUE THREAD

**Issue by steinarcook** [difi/oxalis#5]
Currently the signature in the SMP response is checked. However; since there is no way of inspecting the chain of trust for the SMP certificate, there is not much preventing an impostor ("man in the middle") from signing with a self signed certificate.

**Comment by teedjay** [comment]
Some fixing was done in https://github.com/difi/oxalis/pull/223

**Comment by klakegg** [comment]
Fixing is completed with Oxalis 4.0-RC2.
